### ISSUE TITLE
take off the cooldown on >picks

### ISSUE THREAD

**Issue by thegodofall123** [Kwoth/NadekoBot#1011]
please take off the cool down on >pick it just makes people spam more and i do not like it when you had no cool down on pick  it was better but now because of you it makes more spam

**Comment by shikhir-arora** [comment]
You can change this in the database.

In order to open `NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db` (1.0) or `data/NadekoBot.sqlite` (0.9.x), you need to download and install sqlite browser from here <http://sqlitebrowser.org/> Open the database with it, make changes to any settings you want and click on "write changes" at the top.

Edit the BotConfig table entry for cooldown.

**Comment by thegodofall123** [comment]
oh ok now thanks for your help 0/10

**Comment by thegodofall123** [comment]
wait

**Comment by thegodofall123** [comment]
ok so what if you dont host the bot your self what do you do then O_o

**Comment by shikhir-arora** [comment]
Sorry, I assumed you hosted the bot. You can ask @Kwoth but I don't think they'll remove the cooldown as it affects all servers, with the size of Nadeko it is there for a reason.

**Comment by thegodofall123** [comment]
your really nice and i just insulted you whoa
