### ISSUE TITLE
(Feature Request) Improve word filter

### ISSUE THREAD

**Issue by bambam922** [Kwoth/NadekoBot#1045]
Hi there, 

I run a decently sized server and we are needing to filter out words, but it isn't going so great.
I find the word filter lacking because it is extremely easy to bypass.

I would like to suggest an upgrade to the word filter in which special characters such as á é í etc. are dealt with and that spaces between letters are ignored.

Let me give an example with the word Nadeko.
Say Nadeko is a banned word, but users are bypassing the filter by typing N a d e k o. The word filter should ignore the spaces between the letters and read N a d e k o as Nadeko.

If a special character is used, treat it as a variable. So if Nadéko is used, the bot reads it as Nad*ko and uses the * as a variable letter and searches for it in the list of banned words.

I hope this is something that can be implemented quite easily.

Thanks for considering it!

**Comment by alexratman** [comment]
Could this also be achieved by adding regex support to the word filtering? Or having regex filtering as a separate command?

**Comment by Kwoth** [comment]
Regex filtering won't come. I will probably just find a way to let you use *, so you could do

*N*A*D*E*K*O*

But that would also mach N........32jf32fij0..........A.............D.........E...........f97h2393h9.........K................... ?aad23d23q...... ..........O, or make it just take a single letter, but then N  A  D  E  K  O would still be allowed (double whitespace). Any thoughts?

I guess I could add regex filtering but only for bot owners, because regexes can be very expensive and abusable.

**Comment by Kwoth** [comment]
Moving this to future to wait for some suggestions/ideas

**Comment by Jukuu** [comment]
https://regex101.com/r/VpItfH/4/ something to take in to consideration

**Comment by Kwoth** [comment]
Please move this to http://feathub.com/Kwoth/NadekoBot
