### ISSUE TITLE
[Feature Request] Vote-to-Skip in Music

### ISSUE THREAD

**Issue by EthanChrisp** [Kwoth/NadekoBot#1058]
Similar to SexualRhinoceros' Music Bot (https://github.com/Just-Some-Bots/MusicBot),

It'd be great if we could get a Vote-to-Skip command for the currently playing Song. Could do !!voteskip or !!skip would be a vote-to-skip, and !!forceskip would force skip.

**Comment by samdivaio** [comment]
I am seeing the request after a while,
It's actually discouraged by the a lot users because it makes the music listener uncomfortable to skip when s most of the people are afk/in game and want the music skipped but the only guy on discord. So `!!skip` was made equal for everyone (unless ofc you set perms to block rogue listeners) and we never looked back. 
With my personal experience it saved me from listenin to my friends crappy songs which was never possible with vote-to-skip.

**Comment by EthanChrisp** [comment]
Fair enough, I could see the concern there. Not saying to using `!!voteskip` as a replacement for `!!next`, but it'd be nice if the option was there. Not necessarily geared toward listening with friends, but for those of us who run a large public server and would like to allow users to vote to skip if they do not like the currently playing song, and a Moderator can come in and force skip if needed.

**Comment by Kwoth** [comment]
we had this one a LOT. When we think of the good system for it, it will be added. Atm all effort is spent on making the bot translatable.
