### ISSUE TITLE
[Feature request] MemeTrades intergration

### ISSUE THREAD

**Issue by CallyyllaC** [Kwoth/NadekoBot#1097]
Hey there,
Think it would be cool if it had memetrades integration, just as a little bit of fun.
No real reason or need for it but that doesn't mean it wouldn't be fun without it.
https://memetrades.com/apidocs

Thanks for consideration :)

**Comment by shikhir-arora** [comment]
Just a note that if this is done with the authenticated API (for buying/selling), it would require every user who is self hosting to likely get their own API key due to the following:

> All queries are rate-limited at 1000 per day

And that authenticated API restriction would also make it unsuitable for the full integration to be feasible for Nadeko public.

**Comment by CallyyllaC** [comment]
That's fine it was just an idea at the end of the day

**Comment by QuadmasterXLII** [comment]
Memetrades dev here. We've removed the rate limiting

**Comment by shikhir-arora** [comment]
@QuadmasterXLII The problem I see is not with that (which is why I crossed out my original comment in the edit), but that if this was done even with just the self-hosters (let alone public bot), since each user needs an API key for their own account, there would be no reasonable way right now from Discord to have every user in every guild using Memetrades to securely input their key. It's not a per bot thing, but rather a per user thing. Correct me if I am wrong.

**Comment by QuadmasterXLII** [comment]
I think you are right- it would be a security issue for the bot to store everyone's api keys

**Comment by Kwoth** [comment]
No it's not a security issues, unless you don't trust the bot owner, yeah. I will take a look at this when finalizing 1.3, but most likely it will come in the future, if ever.

**Comment by CallyyllaC** [comment]
Okay, thank you for the consideration :)

**Comment by Kwoth** [comment]
well, unfortunate, just wanted to work on this but memetrade is down. Moving to future

**Comment by Kwoth** [comment]
Please move this to http://feathub.com/Kwoth/NadekoBot
