### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TristannCx** [Kwoth/NadekoBot#1102]
Is it possible to have **.chatmute** work without **Manage Roles**? It would let a moderator like role be able to use the command without being able to touch role permissions.

**Comment by shikhir-arora** [comment]
Yeah, +1 to this personally. This is a good idea that is implemented on some strict-moderation bots because you can assign moderators or admins and have the bot do all the banning, muting, kicking, etc. It's meant so that you have full control over the permissions and is indeed a safer approach. 

Though at that point, it would just involve rewriting and making a permission system - if it's for `.chatmute`, then the same basic concept (and code) would be used for a general system. The only issues I see with it are that it requires a rewrite and change of type into permissions-based which will get a lot of people confused, especially if it's required. But I do agree that it is safer to let the bot do the actions if you assign verbose permissions.

**Comment by samdivaio** [comment]
Done. Mute texts + voice now needs Manage Messages + Manage Mute (voice perms).
Same with chat and voice requiring just Manage Messages and Mute respectively.

**Comment by shikhir-arora** [comment]
@samdivaio with some heavy moderation bots the idea is that it is bad to let users do manual kicks/bans because these bots keep logs, for example, of when and who bans who (as Discord still hasn't released their logging stuff) -- but obviously you need to use the command on the bot for that to log properly. So the idea is that if you assign a Moderator or Admin role to these role ID or user ID's, which can just have a role with no extra permissions, the bot will do all the actions and that way you have more "control" over staff, less chance for potential abuse (as not everyone needs certain permissions) and the entries are logged so it's kept very organized.

**Comment by samdivaio** [comment]
Like you said before we already have a perms system so I believe the only thing we can do is:
- Lower the perms needed to use a command. (such as manage messages least)
- Disable Administration module disabled by default so only the selective roles can use it.
- Check if its possible (getting Kwoth in this part) to remove all the perms requirements so it can be usable by anyone with just the role perms in the perms module that way it can be helpful for logging purposes. 👍

**Comment by shikhir-arora** [comment]
> Disable Administration module disabled by default so only the selective roles can use it.

That is probably fine in all honesty, but the only issue is that people are going to be potentially confused at the change. The actions we're talking about are almost always related to moderation (so that module), not really anything else, though they technically can be.

**Comment by samdivaio** [comment]
Anything we change will definitely gonna confuse old users, for example if we lower the requirement they will be surprised to see why a low level role user with minimum perms accessed the command.
Disabling Administration for new users will prevent that from happening however old users are still gonna get some trouble, same with if we make another role requirement for administration module.

**Comment by rjt-rockx** [comment]
Having Administration module disabled by default doesn't seem like a good idea to me, given the module is one among the most used modules in Nadeko, if not the most used one. Disabling it would just mean more usability issues for people new to the bot.

**Comment by samdivaio** [comment]
With that being said, I think the error message with perms module should be a lil more detailed, saying just some perms is preventing the action isn't enough. Thanks

**Comment by samdivaio** [comment]
I think I am gonna go the @shikhir-arora idea here, while disabling the administration module on default we need to have a criteria that only a certain role access the module and never the @everyone role.

**Comment by rjt-rockx** [comment]
I see potential problems in basing Nadeko's Admin commands entirely on the Nadeko Permissions module, since people would be more used to Discord's Graphical Permission system. Plus, doing so might allow bot owners to exercise control of and maybe even misuse their bot in the servers the bot is in, which would be a huge problem.

**Comment by shikhir-arora** [comment]
The usability is a real concern that I bought up yeah, that is the only real concern honestly.

There isn't really more abuse because a server owner could just give people Kick permissions if he/she wished anyways, without any bots. This just limits that, so they *have* to be on the botlist and can't use Discord's system to do it. The only reason I mention that method is because it's employed in heavy-moderation tools purely for organization - keeps logs of who did what, and forces people to, say, add a warning for a user. Otherwise, people can just right click and it's not logged (who did it) or follow guidelines, etc.

**Comment by rjt-rockx** [comment]
Having a default Admin / Moderator role would indeed help, it has been implemented in quite a few mainstream bots effectively too. But yeah other than places where heavy moderation is required, this won't be of much use. 
Plus, most servers that tend to use such heavy moderation would likely prefer to have a self hosted build rather than the public bot citing privacy issues.

**Comment by shikhir-arora** [comment]
Valid concerns. That's why I said it shouldn't be put too priority. If it's an easy thing to do *while* maintaining usability, then it's great, otherwise it shouldn't be implemented. The usability is the concern I had from the beginning as making a switch like that is a major change of module type, or even the core of the two different "types" of systems.

**Comment by ManuelFte** [comment]
Maybe if the permissions module had an option to work with Discord's permissions and not only with users, roles and channels; like:

`;dc >gc enable ManageMessages
;sc >gc disable`

This way the permissions table would have certain commands disabled by default and enabled only for users with certain Discord permissions, and administrators would be free to change them as they please. Not sure how that would work for current installations though.

**Comment by shikhir-arora** [comment]
Yeah, it's a bit tricky to change. Another **huge** (IMO) point I forgot to bring up that I know comes up a lot in why the whole bot doing the mod action is a good thing is that many users, unfortunately, don't fully understand the hierarchy system and importantly the fact that channel permissions override those (for non-Admins) - so a user can mistakenly set up his/her guild with what they think is a role that doesn't have manage channel permissions, but accidentally put it there for the channels themselves since it often is confusing. These are all the reasons why the bot-role system works, because it eliminates the need for users to do the permissions: bot has admin permissions, you assign positions that the bot has given implicit permissions to internally, then *the bot* checks if the user has the permissions to execute the command and if the user does, then the bot handles the rest. The users can be put in a role just above everyone or whatnot, and the server owner need not worry about specific individual channel permissions. That + the logging benefits and organization. Again, sadly not a seamless switch, but it's a cool thing for sure that I am a big proponent of.

**Comment by Kwoth** [comment]
Actually sam has a point, if someone PRs this  I'll accept it
