### ISSUE TITLE
Nadeko runs for a while but then crashes as can't access src

### ISSUE THREAD

**Issue by dark-falz** [Kwoth/NadekoBot#1119]
This is the error it gives me;
`sh: 5: cd: can't cd to NadekoBot/src/NadekoBot`

Nadeko starts so it must be able to access this? Then just stops completely after around 30min or so.

Tried asking in Discord but no help given; asked to run Nadeko manually w/o tmux but I run other things on my server so I cannot do this.

**Comment by samdivaio** [comment]
Were you using the auto run scripts manually or with the linuxAIO?

**Comment by dark-falz** [comment]
Hi, I'm using the AIO

**Comment by samdivaio** [comment]
Well if you didn't use any other command along with it, its hard to figure out what went wrong for you.
Also about bot going down, it could only go down due to api dead lock or very low memory.
Can you provide us more detail about your OS, version, name of VPS and IP region you can also DM me in Discord if you want.
