### ISSUE TITLE
about ~autohentai

### ISSUE THREAD

**Issue by kotaka773** [Kwoth/NadekoBot#1143]
When i type it nothing happens its not even in the -h list but its in the online commands list so im asking is this command removed or ?

**Comment by xnaas** [comment]
Are you using the public bot or hosting yourself? If it's the public bot, $10 says it's disabled. 😛

**Comment by infy147** [comment]
The ~autohentai command is limited to self-hosters only and cannot be used with the Public version of Nadeko (The one you'd get from here, carbonitex, etc.) (Nadeko#6685), due to the spam it would cause the public bot over all our servers. It's on the command list because if you self-host Nadeko, you can use it (if you want to learn how to do that, check out [the guides here](http://nadekobot.readthedocs.io/en/latest/)~!
