### ISSUE TITLE
[Feature request] multiple commands

### ISSUE THREAD

**Issue by nnever** [Kwoth/NadekoBot#1152]
I often find myself making big lists of commands to run for stuff like permissions and adding music/playlists. It would be nice to run multiple commands in one message like:

"-multi !!q test1, !!q test2, !!q test3, ;chnlmdl Music disable general, etc"
or for executing the same command multiple times like
"-multi !!q test1, test2, test3"
I think this would work really well with command aliasing and it would make first time setup a lot easier.

**Comment by shikhir-arora** [comment]
There will probably be some form of regex support for botowners, that will end up allowing some usage. There is already an alias system that Kwoth implemented and is fairly recent. For abuse purposes it won't let you execute commands that are heavily dynamic (say `!!q`) - but it can set any alias for a *specific* thing like `!!q some song`

Having arbitrary control is very abusable. With the multiple commands thing, I am a bit confused. Because with most commands - say `!!q` again, if you want to queue three songs, doing `!!q song 1, song 2, song 3` is not terribly faster than pasting it. The limitations are still going to be the same. There are just abuse cases that can come up (`.ban user1, user2, user3`) and it can get a bit confusing to separate.

FWIW, there should be a search option shortly on the music module that lets you pick from a short list. :-)

**Comment by nnever** [comment]
fair enough, tysm
