### ISSUE TITLE
.prunechannel, a new command (request)

### ISSUE THREAD

**Issue by Creepso** [Kwoth/NadekoBot#1159]
Add a ".prunechannel"
Usage: .prunechannel [Name of channel] [number of messages] [What Time to delete]
Ex: .prunechannel roles_requests 100 10 = Execute the command in "roles_request" channel, that will delete 100 messages and will delete 100messages every 10sec.

**Comment by Kwoth** [comment]
no

**Comment by Creepso** [comment]
Ok then... That was a nice command... Really helpful with servers with "registration" system

**Comment by ManuelFte** [comment]
A command like that would probably get your bot banned by Discord due to exceeding the rate limit. For your registration channel you can deny Read Message History permission to all users so they don't see past registrations; or deny Read Message permission to registered users so they no longer see the channel at all.
