### ISSUE TITLE
(dev) Shop isn't working properly

### ISSUE THREAD

**Issue by Plajer** [Kwoth/NadekoBot#1174]
Shop module added in dev version of NadekoBot doesn't work properly. When i add role to buy for 800 flowers and i want to buy it for 800 it takes only 80 flowers. When you have less than 800 it tells you that i haven't got enough flowers.

**Comment by Kwoth** [comment]
First, update to latest, there was a bug which refunded purchases to the buyer, not the seller. Second, if you buy the role yourself, it will take 800 from you, and then refund you 720, because you're the one who set up the shop. The one who made the item gets the profit. When other people buy the role for 800, you will get 720.
