### ISSUE TITLE
Logserver on multiple servers

### ISSUE THREAD

**Issue by Jonz00r** [Kwoth/NadekoBot#1187]
Logserver seems to lose track of server context after restarts. I have added .logserver enable as startup commands after making the bot its own owner. I have been experiencing http://i.imgur.com/JSxSPzw.png
logging is enable for edits but no log is generated. I believe this may be due to having the log running on multiple servers. I have experience many issue like this especially with .log userpresence saying it has stopped logging yet continues showing when people go offline / idle / online / other. not sure what to do at this point.

**Comment by Jonz00r** [comment]
I've also had servers where I use .logserver enable and get the confirmation message yet no logs are generated at all.

**Comment by ttshivers** [comment]
I actually discovered this issue a while ago myself and did some investigation into what was causing it. The issue that is causing this is that the one to one relationship between GuildConfigs and LogSettings is not properly defined. As a result EntityFramework has no idea how to handle the Join, so any server log settings in any server always affect row 1 or LogSettings. The current relationship is not properly defined because there is only a one way relationship with GuildConfigs having a LogSettingsId that is a foreign key. However, there is no link going back a specific LogSettings row to GuildConfigs. I actually looked around the bot and didn't discover any other one to one relationships, so it looks like that this one was just improperly defined because it was the first one used. In order to properly define the relationship, you need to have LogSettings have a foregin key that points back to the GuildSettings row that it is related to. You could even make the foreign key the Id column in LogSettings, but looking at the code, since the Id column is an inherited field, it may be easier to just add another column that is that foreign key.

The reason why any log setting done in any server always affects row 1 of LogSettings is because of this line of code:
```csharp
var config = _set.Include(gc => gc.LogSetting)
                            .ThenInclude(gc => gc.IgnoredChannels)
               .FirstOrDefault();
```
Specifically that `FirstOrDefault` statement. Since the one to one relationship is not defined up to
[EntityFramework's standards](http://www.entityframeworktutorial.net/code-first/configure-one-to-one-relationship-in-code-first.aspx), it doesn't really know which row to include, so it just includes the first one it finds.

**Comment by shikhir-arora** [comment]
As mentioned it might be intentional, since it has been known for a while now and most users only utilize the selfhosted bot for small servers (and the log feature isn't a public Nadeko feature). And there is a large portion of Nadeko users that are not selfhosted, so the issues related to only those features are not high priority, which is fine.

With the current `UserPresence` (online/offline/idle) logging, it is not really possible to do many log servers with any practicality. [It is explained here in a few places, including the bottom commit log dated 10 May 2017](https://github.com/shikhir-arora/NadekoBot/issues/32#issuecomment-300372411)

**Comment by Jonz00r** [comment]
I turn user presence off in almost every case.

**Comment by Kwoth** [comment]
Thanks @ttshivers . Relationship is proper I believe, what's not proper is the code you found. It doesn't use guildId at all.

It should say 

```
var config = _set.Include(gc => gc.LogSetting)
                            .ThenInclude(gc => gc.IgnoredChannels)
               .FirstOrDefault(x => x.GuildId == guildId);
```

I'll fix this on dev in a few moments thanks a lot for finding it.
