### ISSUE TITLE
Question regarding permissions

### ISSUE THREAD

**Issue by Konkz** [Kwoth/NadekoBot#1191]
I want to use Nadeko as a way for my Discord Moderators to assign ranks to people, that way I have log of the Nadeko bot saying that X assigned Y rank to Z. But, it requires the Manage Roles rank, is there a way around it?

Else this command would be useless, as they can give the rank anyway

**Comment by Deivedux** [comment]
I don't think so... It is meant that commands like these suppose to follow server specific permissions, otherwise it's not that it will get useless, but it will get over-abused a lot by anyone on any server.

**Comment by Konkz** [comment]
I was hoping there's an "add mod" command somewhere and I've missed that checks if user is part of X group, and if so unlocks the specific command.

Perhaps for future implementation? For now I sadly will have to find another bot to do this. :/

**Comment by Jonz00r** [comment]
This is the one "flaw" with the permissions system. In what situation would
you give someone manage roles on discord but deny them the command in
nadeko. I really wish there was a nadeko permission mode to ignore server
perms so I can explicitly allow moderation commands ignoring discord perms.
This would be more auditable and controllable until discord audits come
out. currentyl I see no use for createrole, addrole, assign role, kick,
ban, or other such command through nadeko.

**Comment by Jonz00r** [comment]
And while we're at it. if .logserver is enabled it should log use of
administration commands in the log rather than just the fact someone
received a role or other kind of thing.

**Comment by shikhir-arora** [comment]
I am for the moderation by bot (I use a different tool which does that for moderation and fully disable the moderation commands essentially on Nadeko personally), and yes it was discussed a *lot*, but it requires a very large rewrite of the system as it is. 

Then pushing that to users is a **challenge** afterwords. There is too much right now on the plate to do that this moment, unfortunately. And yes, logs don't store the information like who banned who because, in order to _strictly_ do that, the permissions would have to be rewritten as mentioned above and make users utilize the bot for moderation (kick, ban, etc.) - otherwise if a user has regular kick/ban privileges they don't have to use the bot and the bot can't record who did what actions if it's done by the user directly via. Discord.

**Comment by Jonz00r** [comment]
"otherwise if a user has regular kick/ban privileges they don't have to use
the bot and the bot can't record who did what actions if it's done by the
user directly via. Discord."
which is why the kick and ban commands are pretty useless.
