### ISSUE TITLE
[Feature Request] Letting Nadeko Change Nicknames

### ISSUE THREAD

**Issue by Zequew1** [Kwoth/NadekoBot#1195]
I saw the other post about her changing nicknames, but they did it for a very poor reason, this on is for mobile users. When people on mobile are hosting a server, or staff on a server, they cannot change nicknames. This would be a very useful feature, and would help out mobile users!

**Comment by shikhir-arora** [comment]
Having a `.changenick` command limited to yourself for mobile (only the user can do it for themselves) is OK, there are a few bots that can do that on Discord just fine.

Here is why you can't really have nickname-change ability via. a bot for everyone:

- No way to really moderate it, it could be logged yes, but that isn't a standard event, so it would have to be dealt with with on the hope that everyone who could used the bot and did it properly so it was logged.

- But to cut it short: it would be an **extreme** spam event, and can happen if just one random staff member decides to be a bit too drunk or something and mess around. It's just a nick change, so most don't care, but it would cause problems.

- It can and likely will (depending, but if it's a feature for all -- on public Nadeko -- then yeah for sure) inevitably run into ratelimit issues. 

That should end that right there, IMO.

**Comment by CorruptComputer** [comment]
I disagree with @shikhir-arora when it comes to moderation. Discord already has `Change Nickname` and `Manage Nicknames` permissions. Also I don't think people would change nicknames super often with it, honestly how often do people really change their names, and when they do whats the point of using the bot instead of the client when not on mobile?

**Comment by Zequew1** [comment]
@CorruptComputer I disagree with @shikhir-arora as well, I am hosting a bot, my staff is on at different times, but not all of them are online, if someone has an inappropriate nickname, the person on mobile can't do anything about it. This is bad when it comes to popular servers. And why use another bot just to change nicknames? I feel that it would be necessary for Nadeko to have this command, due to it literally having every command other bots have, and it is a competition.

**Comment by CorruptComputer** [comment]
I don't really see it as a competition, why can't they all work together and improve each other so we have a ton of good choices? This is the open source ecosystem after all. But I do agree this would be a useful command.

**Comment by shikhir-arora** [comment]
There are two types of things you have to look at when it comes to this. First, the command itself. If you mean a shortcut like `.changenick` for users to change their **own** nicknames without having to use the client directly, as @Zequew1 mentioned in the original post, then that's absolutely fine. Yes, the bot will change your nick for you in that case, but _only_ you. This exists on some moderation bots. This is not a bad feature to have for ease of access for the user through the bot, sure.

It becomes an issue when you want to make it a universal command for the reasons I mentioned above. `MANAGE_NICKNAMES` is a relatively "low" command on the hierarchy of things. Nadeko is a very large bot, and unfortunately some people use it for a lot of malicious things. Right now it is very hard to spam change nicknames because you would have to do it by hand. The minute it becomes a command, it can easily be edited. Even if Nadeko's source has a line that limits the frequency, it will be edited by someone and likely used to change nicknames at a *much* faster rate. With public Nadeko, which has over 70,000 servers, >100 commands/second issued, and over 400,000 text channels, it becomes very apparent that ratelimits would be hit. It already happens for other events that are less prone to this.

It's not about the competition or choices, but about seeing if something is practical for a bot this big. And just so you know, the endpoint for `guild_member_nick` is a 1/second guild-wide ratelimit, and it's one of a few endpoints that Discord specifically mentions with its own ratelimit (not shared with other API endpoints towards the global ratelimit).

With regards to logging, changing nicknames is now part of the Audit Logs, which is good. But my concern was more with the spam -> ratelimit which would happen no doubt. If the command is restricted to just respond to users, like I said, I have no problem with that at all.

**Comment by Kwoth** [comment]
rjt - 04/06/2017
.setnick command
Usages:
.setnick Nickname - Sets the bot's nickname. Requires Manage Nicknames permission.
.setnick @user Nickname - Sets the nickname of the mentioned user to the one specified in the argument. Requires Manage Nicknames permission.

**Comment by Zequew1** [comment]
You're the best man, thx for this.
