### ISSUE TITLE
Deletion of many Messages [Again]

### ISSUE THREAD

**Issue by ModdyLP** [Kwoth/NadekoBot#1215]
Hello i posted a few month ago, that it would be nice to make a workaround the Discord Limit of 2 weeks deletion. 

> I have an idea how to fix that issue, you can get the messages from the channel and delete all message seperated and not as bulk. The two weeks rule is only for bulk messages not for deleting messages seperated. I know it will take longer to delete all messages, but i think it would be helpfull. 

> Also please add a message for the user, which say the cause of the problem.

I hope you can add it, i would add it on my own, but i dont know much about this language and dont want to mess up something. 

I hope you read and think about my idea. It would be really nice if you can implement this options.

**Comment by shikhir-arora** [comment]
This is not a bad idea and fine for a smaller thing/private or some self-hosted, but it becomes a pain for the public bot. The `BULK_MESSAGE_DELETE` endpoint is specific and per-channel, which is unique and allows bot accounts only to delete very fast, and per-channel thereby avoiding ratelimit issues.

There is no special exemption for this for bots, and they would use the same `MESSAGE_DELETE` endpoint as you or I would, and the ratelimits would be towards the global as well, so it would be very slow - especially in large public bots.

I do this privately - not with Nadeko - but this doesn't seem to be worth it since the public bot wouldn't reasonably be able to do it without API abuse, and timing it is a few extra bit of work (BULK until hits 2 week, then delete slowly) as you would need to keep track of the channel and global ratelimit - if not it will turn messy very fast.

**Comment by ModdyLP** [comment]
I dont need that it will be deleted fast. Slowly is acceptable. Sure, the public bot cant handle that, but i would like it for private hosted bots like mine, that there is an option to slowly delete a huge amount of messages

**Comment by Kwoth** [comment]
You will be able to delete up to 1000 messages, regardless of their send time in `1.43`
