### ISSUE TITLE
Music playback stuck on loop

### ISSUE THREAD

**Issue by Cornelious11** [Kwoth/NadekoBot#1354]
Songs are no longer removed from queue when finished playing, running `.rpl` reponds with message that the queue is turned off repeat, however the queue is still not cleared. These issues started occurring after migrating from version `1.51` -> `1.53` and have persisted through subsequent builds. 

1. **Version** 1.54b
2. **OS** Windows Server 2016 14393.1358
3. **Ffmpeg** Installed from updater
4. **Youtube-dl** Installed from updater

**Comment by Deivedux** [comment]
iirc, this is a new update from Kwoth saying that the song will no longer be removed from the queue once played, instead use `.smr` to remove specific songs from the queue.

**Comment by ManuelFte** [comment]
It's not an issue, that's how it works now. The music module experienced many changes in Nadeko 1.53; specifically:

● `.stop` doesn't clear the queue, use `.srm all` for that. Stop just goes back to the first song, and stops the playback. Using `.q`  and `.lq` will notify you that player is stopped to prevent confusion. use `.play` to resume.
● Note the difference between pause and stop: `.p` pauses current song and you resume it with `.p`, if you use `.play` when song is paused, bot will play the next song.
● Shuffle will now show in `.lq` at the top, and instead of shuffling playlist, it will randomly jump to a song in the playlist after current one is done.
● `.play` command added - Acts as `.n 1` if no arguments are specified. If you specify a number, it will play a specified song (eg.`.play 5` will play 5th song in the queue). And if you specify a query string, it will act as a `.q song name` command.
● `.move` will cancel the current song, I just advise you to move the bot manually (by dragging it).
● `.lq` will show most enabled options at the top or the bottom).
● `.rpl` will be enabled by default, since songs no longer get removed, you will still be able to disable it which will just cause the player to stop when it finishes playling the last song.

If you have any issue please report it on our support server to confirm that it's indeed a bug and not something else: https://discord.gg/0ehQwTK2RBjAxzEY
