### ISSUE TITLE
Fairplay Issue

### ISSUE THREAD

**Issue by samdivaio** [Kwoth/NadekoBot#1389]
- Fails to play the next users queued song.
- Randomly picks previously played songs.
- Causing a loop sometimes.

**Comment by Aerysch** [comment]
Can confirm, in my case it usually jumps back to the first song in the queue list.

**Comment by GMR516** [comment]
Having this issue as well. Anyone else?

**Comment by Macley-Kun** [comment]
Wondering if there's an update on this~~

**Comment by GMR516** [comment]
Still broken.

**Comment by Macley-Kun** [comment]
Hacktoberfest is over :p

**Comment by GMR516** [comment]
And it's still broken.

**Comment by floopfloop** [comment]
The cause of the issue seems to be that the fairplay code grabs a copy of the playlist, shuffles it and then finds the index of a fair song. The index gets passed back to the musicQueue object, however since the index was based on a shuffled queue and the original queue remains unchanged, in the original queue the index is not really fair.

If the shuffle is removed from the fairplay code, it would fix the index mismatch problem, but then the player would loop through the first added song of all the people on the list. Having sad(song auto delete) enabled would be an easy way to get the intended behavior.

**Comment by Kwoth** [comment]
@floopfloop thanks for the insight :) I will look into it.
