### ISSUE TITLE
.ban command is not working

### ISSUE THREAD

**Issue by cabi4** [Kwoth/NadekoBot#1412]
I tried multiple times on my server, Nadeko have all permissions (even more than administrator have) and nothing work, .b doesn't work .ban also, I try to ban someone in the server doesnt work, I try to ban someone outside with ID doesn't work also ... someone from player support in the server told me to ask there. samvaio#5797

**Comment by samdivaio** [comment]
Wait, *"I try to ban someone in the server doesnt work"*? really?
Are you the server owner, if not then check your roles perms and if you are make sure the users are below the bots role.

*"I try to ban someone outside with ID doesn't work"* yeah its not working, probably because of some discord changes. Needs investigation.

**Comment by Kwoth** [comment]
No, it's working. Recheck yours and your bot's permissions. You can't ban people who are not yet on your server.
