### ISSUE TITLE
I can give the same role  as an assistant mod to others with .sr but I can't remove it with .rr

### ISSUE THREAD

**Issue by whitebeard66** [Kwoth/NadekoBot#1434]
First of all I shouldn't be able to give the same mod role I have to others, second of all I can't remove it with .rr

**Comment by ItsFriday** [comment]
Can you paste your perms here?
It should be that one role should be lower than the other
then they shouldnt be able to give them a higher role.

**Comment by ItsFriday** [comment]
If you have discord, I can try to take a look, give me an add "Hailie's King ♡#7326".

**Comment by whitebeard66** [comment]
![screenshot_20170722-213413](https://user-images.githubusercontent.com/30372894/28494119-9dfc9c3c-6f25-11e7-8787-977a090b50f1.png)

**Comment by whitebeard66** [comment]
You meant this I hope

**Comment by shikhir-arora** [comment]
That is the channel permissions in that channel, which are different than global (or can be/often are) - if you have "Manage Roles" global permissions, then you should be fine giving your role to others - as long as you aren't assigning a role *higher* than yours. But if you have global access to do so, you can manage roles at or below yours, so that can include the mod role you have.

You can't remove it because it's likely your highest role. Can you see the role list? Check and see if your mod role has a lock next to it. It is likely that is your highest role, so removing it would be like removing your access to even do it - so it won't let you.

**Comment by ItsFriday** [comment]
+ Nadeko allows a user with the same role, to give that role to someone regardless of it being the highest role that person has.
+ Nadeko does not show the user its a permission issue.
Confirmed on his server.

**Comment by willysunny** [comment]
Could you be a bit more clearer? Better with a sample case

**Comment by Kwoth** [comment]
I still have no idea what is this about.

**Comment by Kwoth** [comment]
Ok you will no longer be able to that from 1.6.4
