### ISSUE TITLE
.die no longer works?

### ISSUE THREAD

**Issue by Lumanator** [Kwoth/NadekoBot#1618]
When I was trying to exit the program by typing ".die", it doesn't seem to work anymore. It could probably be on my end tho.

Update: The bot somehow no longer works in my channel either. DM's work fine tho.

**Comment by Kwoth** [comment]
Update it. If you added channel categories you must update to 1.8+

Update your bot to 1.8+

If you're on linux you need to use this link

first, backup your current installation just in case

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.4/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites
2. Download nadeko (first option)
3. Run nadeko

(Keep in mind this installation script will change again soon (1.9 instead of 1.4) for 1.9+ installations
