### ISSUE TITLE
MacOS build fail with NadekoBotv1.9

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1630]
3 cases:

1. me. MacOS v10.12.5. Hundreds of warnings and thousands of errors on build.

2. tia#5268. MacOS v10.12.5. Build succeeds but owner channel connection fails
```Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:08.82
21:11:03 NadekoStrings | Loaded 23 languages (da-dk,fr-fr,zh-cn,zh-tw,nb-no,he-il,sr-cyrl-rs,ja-jp,ro-ro,ru-ru,ar,id-id,de-de,tr-tr,nl-nl,pt-br,pl-pl,it-it,en-us,sv-se,cs-cz,es-es,ko-kr) in 0.12s
21:11:03 ImagesService | Loading images...
21:11:03 ImagesService | Images loaded after 0.12s!
21:11:03 NadekoBot | Starting NadekoBot v1.43
21:11:03 NadekoBot | Logging in...
21:11:04 NadekoBot | Waiting for all shards to connect...
21:11:08 NadekoBot | Loading services...
21:11:08 PermissionsService | Permission version is 1, upgrading to 2.
21:11:09 PermissionsService | Loaded in 0.66s
21:11:09 CustomReactionsService | Loaded in 0.03s
21:11:09 NadekoBot | Connected in 5.69 s
21:11:09 NadekoBot | 
Author: [Kwoth#2560] | Library: [Discord.Net]
Bot Version: [1.43]
Bot ID: 325454130036473856
Owner ID(s): 120106739637944320
Uptime: 0 days, 0 hours, 0 minutes
Servers: 1 | TextChannels: 0 | VoiceChannels: 0
Commands Ran this session: 0
Messages: 0 [0.00/sec] Heap: [17.83 MB]
21:11:15 SelfService | No owner channels created! Make sure you've specified correct OwnerId in the credentials.json file.
```
`credentials.json` was not touched between update, but still validated anyway. Is valid.

3. Ragnarok #1268. MacOS v10.12.6. Exact same issue as me. I had him use 1.4 linuxAIO.sh, and he is stuck on creating owner channels.

All dotnets are the [correct version](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md), old versions were [uninstalled](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh) correctly

All dependencies are installed and up-to-date.

I have done a clean install of NadekoBot v1.9, still doesn't work.

**Comment by Kwoth** [comment]
That's the wrong version of dotnet btw. You need .net sdk 2.0, maybe @samdivaio knows why mac stuff doesn't work.

**Comment by samdivaio** [comment]
The first error you mentioned is due to read only file system bug which isnt very complex to fix.

Second one is probably related to discord categories feature so you gonna have to update the bot to past 1.8 versions.

For 1.9 you require redis along with the [latest .net core sdk](http://www.microsoft.com/net/core#macos) as Kwoth mentioned. 
So you gonna have use `brew install redis ` on your terminal app and to check if its installed use the command `redis-cli ping ` it's should reply `PONG `, close the cli with just the `exit ` command.
If you find the redis is not auto started after the installation you can check a nice guide [here](https://medium.com/@djamaldg/install-use-redis-on-macos-sierra-432ab426640e) and follow it.

**Comment by MaybeGoogle** [comment]
ohhhh I see. Before, dotnet 2.0 didn't work and 1.x was required. I had redis installed, but not running. 

Thanks so much. I'll tell the others.
