### ISSUE TITLE
Nadekobot can't find .autohentai or .autoboobs

### ISSUE THREAD

**Issue by repta45** [Kwoth/NadekoBot#1753]
I tried typing in the command like the command list says and I even turned on every single permission for nadekobot. I even typed .h .autohentai and .autoboobs and it says nadekobot can't find that command. Am I doing something wrong?

**Comment by MaybeGoogle** [comment]
If you arent selfhosting the bot, this is because those commands are disabled on the public bot.
If you are selfhosting the bot, reply back or something.

To learn how to selfhost nadekobot, find the right guide [here](https://nadekobot.readthedocs.io/en/latest/). If you need help with doing that, here's the [help server](https://discord.gg/2uujW5).

**Comment by repta45** [comment]
No, I don't think I'm self hosting, so I'll check out the link
