### ISSUE TITLE
Currency no longer supports gif

### ISSUE THREAD

**Issue by Macley-Kun** [Kwoth/NadekoBot#1807]
Previously nadeko supported gifs when you issued the `.pick` command. But now it no longer does.

Confirmed that due to recent changes this has happend thx to @Gremagol

**Comment by Gremagol** [comment]
Yes, can confirm. The Source makes every image a PNG file, which doesnt support animations like gifs do.

**Comment by shikhir-arora** [comment]
Not the most elegant or official fix, but a quick one is to  just change `"plant.png"` to `"plant.gif`" on this line and it will work fine with GIFs. The other images (non-GIFs) will display fine even though they're not GIF's since this is just a filename and can be anything (the actual MIME data is preserved in the original image).

https://github.com/Kwoth/NadekoBot/blob/607decfbcc45b216f2ffdcc2b8d0d8f4ba0a6859/NadekoBot.Core/Modules/Games/PlantAndPickCommands.cs#L94

**Comment by shikhir-arora** [comment]
Not a bug, but @Kwoth may want to do it a different way. You can detect the image format if you wanted, but again this was just a quick one-minute fix and doesn't really matter. But will leave it to Kwoth to close.
