### ISSUE TITLE
flowers/currency - custom image - only appears when mouseover

### ISSUE THREAD

**Issue by manonillusts** [Kwoth/NadekoBot#1937]
hi, i have a pretty low res image in .png format set to replace the normal flower images, and it works perfectly fine.

but the issue is that the image will only appear on mouseover, it doesn't load itself and stay there.
why is this?

**Comment by shikhir-arora** [comment]
It shouldn’t be like this, but the reason could be that we changed the logic so the images display as GIFs. Even if they’re not GIFs, they display as such just for backward compatibility. If you use a higher res photo, does this solve your issue? Basically a non-GIF can display fine as it’s just a format — but that may explain it. Let me know if you get the same issue with a larger image.

**Comment by Macley-Kun** [comment]
I've bin testing it out but. I just wait a second or so more. And it appears. Maybe you should ask this question to the discord developers. It seems they changed some things around that. I also notice the load gif is in the top left corner instead of in the middle.

**Comment by shikhir-arora** [comment]
@MaybeGoogle I haven't noticed many major changes but if there are then it's probably due to this [change last month or so](https://blog.discordapp.com/how-discord-resizes-150-million-images-every-day-with-go-and-c-c9e98731c65d) that Discord made (switching their image resize system to [lilliput](https://github.com/discordapp/lilliput) 🙂  Pretty cool stuff.

Though this is at least 1-2 months old now.

**Comment by MaybeGoogle** [comment]
Wait y did u tag me <.<

**Comment by manonillusts** [comment]
![img1](https://user-images.githubusercontent.com/34617610/34087864-ba54a10a-e3f5-11e7-870b-9fd6a744ebc9.png)
i am using this image, its a 2mb .png file not a gif, but as shikhir said it displays it as a GIF  anyway, which is why I think it does not work.. since discord leaves gifs until you mouse over them

**Comment by shikhir-arora** [comment]
@MaybeGoogle by accident xD, sorry! 

@manonillusts That's done because of how images are stored in redis cache. The fix was to make it show up as a GIF, otherwise GIF's wouldn't work natively. This was done quite a while ago now (1 month or so AFAIK). Will need to investigate when I have time or someone else can, because it's not a huge issue right now.

**Comment by manonillusts** [comment]
@shikhir-arora idk why its not working for me though, if i go into the nadekobot discord, her little welcome/help message has a gif of nadeko, but it actually loads properly and is a still image until mouseover, whereas mine is just invisible until mouseover ><

**Comment by shikhir-arora** [comment]
Because if the GIF size is too big then Discord will likely not display it. Try using a smaller image.

**Comment by manonillusts** [comment]
ok i will, thanks for the tip ill try that

**Comment by manonillusts** [comment]
@shikhir-arora that worked... i made it a 286kb jpg and discord loaded it properly now. that's weird, i never knew that it veto'd any higher file sizes (cuz 2mb wasnt that high)

**Comment by shikhir-arora** [comment]
Yeah, Discord has a limit, not sure 100% what it is for GIF displays. This is because it would be intensive to display large GIFs. A 2MB GIF is big in the GIF world, technically, if it was a real GIF.
