### ISSUE TITLE
Failed to parse Int32 / Int64

### ISSUE THREAD

**Issue by MelioettaZyguard** [Kwoth/NadekoBot#1946]
Hi, I just updated nadekobot from version 1.7 something to the latest as well as installed Redis.
I'm having both "Failed to parse Int64" and "Failed to parse Int32" on almost all commands that requires tagging someone in it. Do I need to do a reinstall or is this some setup issue ?

**Comment by shikhir-arora** [comment]
Can you show us a screenshot? Preferably both of Discord and your console/terminal. 🙂

**Comment by MelioettaZyguard** [comment]
https://imgur.com/rAW9jqR

All older versions of Nadekobot worked properly on this server (and others as well) that I had the bot on.
Also I'm not sure why it says $flip is the command on the command list but the bot only accepts .flip instead. I'm pretty sure I didn't change any command settings and I did a clean reinstall when the bot was moved to the new updater.

**Comment by tukimoop** [comment]
Number before name. So you need to do `.take 100 @Name` instead of `.take @name 100`.

As for claim, you need to specify a number as well, since you're claiming with the amount of flowers.

For flip, you're either looking at a very old commands list or not an official one. You want this one. https://nadekobot.readthedocs.io/en/latest/Commands%20List/
