### ISSUE TITLE
Nadeko won't log in

### ISSUE THREAD

**Issue by Aristomenes** [Kwoth/NadekoBot#1956]
I'm trying for days to set up my own bot and I followed every instruction (I think). I set up the credentials, I reinstalled redis. But it won't log in. I've waited several hours, but it just restars the log in process without coming online.

![nadeko](https://user-images.githubusercontent.com/34884438/34378489-54779498-eaf6-11e7-80df-8a856e87d2ef.JPG)

I changed my firewall settings, but nothing works. Don't know what else to do.
Thanks in advance.

**Comment by Macley-Kun** [comment]
Firewall and anti-virus are both off?

**Comment by Aristomenes** [comment]
yes

**Comment by Macley-Kun** [comment]
runned as administrator? Double checked you can use discord on that machine as well?

**Comment by Aristomenes** [comment]
Runned as administrator, yes. I didn't check, no

**Comment by tukimoop** [comment]
can i point out something obvious here?

that's windows 7, and it isn't supported.
~~stolen from ... win7~~

"Windows 7 is not supported, because Nadeko requires websockets, which aren't available on W7. You can thank Microsoft.

You have a couple of choices here:
1. Use Docker Toolbox, a program similar to a virtual machine. Follow this guide.
2. Install a different OS (such as Windows 10 or Linux)
3. Rent a VPS (virtual private server), which has the added benefit of not needing to keep your own computer on all the time."

**Comment by Macley-Kun** [comment]
Jezus fucking christ are you kidding me 🤦‍♂️
