### ISSUE TITLE
reactions roles

### ISSUE THREAD

**Issue by Arnemetia** [Kwoth/NadekoBot#2029]
Hello,

I used the command .reactionroles, everything works, but several hours after the command, the reactions are no longer in the right order below the message

There is a way to fix that?

Thanks

**Comment by Macley-Kun** [comment]
You did this on the public nadeko or on a selfhosted one?
What does `reactionroleslist` show?

**Comment by Arnemetia** [comment]
on a selfhosted one
.reactionroleslist displays the message above the reactions

**Comment by Macley-Kun** [comment]
in the right order or? i've never used the feature some i'm new to that one :D

**Comment by Kwoth** [comment]
I don't understand the issue. Can you screenshot?

**Comment by theLAZYmd** [comment]
![image](https://user-images.githubusercontent.com/31519537/35704640-12f0be14-0798-11e8-9792-2ab077c8d3c5.png)
So in this image, all of the `.rero`s were originally uploaded in the order written out in the main message (ex: America | Europe | Middle East | Africa | Asia | Australia for the first one) but after a few hours it went to random order. I'm pretty certain the oder changes frequently, and changes between different devices and different people. This obviously doesn't happen with just normal reactions (otherwise how would anyone ever be able to spell anything?) so It must be something to do with Nadeko's `.rero`

**Comment by Midoriin** [comment]
It's a Discord thing, that is not related to the bot.

**Comment by theLAZYmd** [comment]
> This obviously doesn't happen with just normal reactions (otherwise how would anyone ever be able to spell anything?) so It must be something to do with Nadeko's `.rero`

**Comment by Macley-Kun** [comment]
Can we close the issue? This is outisde NadekoBot's doing.
