### ISSUE TITLE
prune and log problem

### ISSUE THREAD

**Issue by AnkokuShizora** [Kwoth/NadekoBot#2031]
I noticed that after i prune a large amount of messages in a channel only a handful if any are traced by Nadeko's logs. For example i recently pruned 57 messages in a channel and Nadeko only traced around 9. Another time i pruned 50 and she didn't trace any messages other than the .prune 50 itself. Seems like she cant show every pruned message for some reason.
Also as a different issue i'd like to report that running .prune without arguments in a channel will only remove all of Nadeko's messages in the last 50 messages rather than 100 that the description of the command claims. To test this i did .uinfo and then proceeded to send 50 different(non-command) messages in a channel. Then doing .prune did not delete Nadeko's message with my info.
Those may be kinda insignificant problems but i thought i'd report them anyway.

**Comment by shikhir-arora** [comment]
The logging is likely due to ratelimits, as the bot has bot global ratelimits and ratelimits for posting -- so catching these in large amounts is never perfect.

The other issue you describe is likely due to the fact that I assume you aren't deleting your commands, so if there's 50 Nadeko messages and 50 of yours (initiating the command), Discord internally fetches 100 messages at a time (at least for users) and so it may be getting stuck in that. I haven't looked though, so it's just a guess.

**Comment by AnkokuShizora** [comment]
I said 50 different(NON-COMMAND) messages because i knew you'd say something like that.

**Comment by shikhir-arora** [comment]
Sorry, I checked and the code right now is set to check 50 messages and not 100 for actual Prune. That’s why you’re seeing that.

And yes Nadeko doesn’t log deleted messages that are its own.

**Comment by AnkokuShizora** [comment]
When it comes to my loging issue the messages i pruned were not nadeko's. I already know nadeko doesnt log the content of her own deleted messages.
The reason she couldn't log all the user messages was probably cause of ratelimit as you initialy said.

**Comment by Kwoth** [comment]
Yea, you can't expect a bot to log messages which are deleted at high frequency. Especially when it's bulk delete.
