### ISSUE TITLE
Bot closing whenever PC is closed

### ISSUE THREAD

**Issue by TheLostEevee** [Kwoth/NadekoBot#2038]
So to access the currency, gambling, and other administrative features/perks, I got Nadekobot to program onto my laptop however whenever I close my laptop, Nadekobot.exe closes and is seen as offline on my Discord. So my question is, how do I host/keep my NadekoBot online 24/7 at all times (Besides keeping my PC on 24/7)?

**Comment by Paril** [comment]
You'd have to run it on a computer that is running 24/7. If you can't self-host it, you will have to run it on a server somewhere else.

**Comment by Macley-Kun** [comment]
Try to google on: how to keep laptop running if lid is closed windows.

If you close the lid then it stays on.

Met vriendelijke groet,

**Comment by shikhir-arora** [comment]
> (Besides keeping my PC on 24/7)?

As @Paril stated, this is impossible -- where Nadeko is hosted _and_ online it must be on a device that is online as well, 24/7.

**Comment by Macley-Kun** [comment]
Google SkySilk. Roll into the beta and verify with a cc. That’s all options you got :D (aside of payed vps’s or asking friends).

**Comment by lilcheo** [comment]
Thx @Macley-Kun but also u cold use 

> Heroku

**Comment by Macley-Kun** [comment]
No. The creator/maintainer doesn’t update nadeko because of personal reasons. Therefore the solution is litterly only handy if your ok running the 1.3b version.

If SkySilk add the swap size as an option, it’s possible to run nadeko free on a VPS. Of course you need a credit card to verify. And using be music module will overflow the memory what is bad xd.

**Comment by Nekiono** [comment]
actually, have a look at nssm for windows to register it as a service.
