### ISSUE TITLE
.stop problem

### ISSUE THREAD

**Issue by AnkokuShizora** [Kwoth/NadekoBot#2043]
.stop empties the queue and makes the bot leave the channel when it should be preserving song index and keep the bot in channel.

**Comment by shikhir-arora** [comment]
I don't use Nadeko for music, but I cannot replicate this issue. I have `.delmsgoncmd` on so that's why you don't see my input commands in the screenshot:

![screen shot 2018-01-27 at 8 31 41 pm](https://user-images.githubusercontent.com/8797918/35478065-40535f06-03a1-11e8-8a27-26236a820107.png)


It does what it says: the bot stops when I do `.stop` -- this can be seen in the second music embed (**"Player is stopped. Use .play command to start playing.**) and it stops that song. No it does not preserve where it stopped as it's not a pause command. But it keeps the track there still. `.play` resumes - or starts the track again. It also has my second queued track there just fine displaying. Again, I don't use this at all, but I have a ton a long time ago and know the module well, and it does seem this command works perfectly fine. v2.13.8 on Ubuntu 17.10.

**Comment by AnkokuShizora** [comment]
I wasn't using .destroy but i just discovered that .stop behaved the way i described because i had .autodc enabled. My bad. Guess i should close this issue or would this also be a considered a flaw considering autodisconnect is supposed to only remove the bot from the vc when its done playing all the songs and not when its merely stopped?

**Comment by shikhir-arora** [comment]
Well, when you `.stop` the song does trigger a player stop. I have to look into that. I will check and see, don’t close this yet.

**Comment by AnkokuShizora** [comment]
Ok. Would like to note that when you do .pause the bot doesn't disconnect from vc even if you have .autodc enabled so im guessing .stop should normally work that way aswell.

**Comment by shikhir-arora** [comment]
If you go to: `NadekoBot/NadekoBot.Core/Modules/Music/Services` and edit `MusicService.cs` 


https://github.com/Kwoth/NadekoBot/blob/b4566b74862742708d0c850132d481cc2cddd286/NadekoBot.Core/Modules/Music/Services/MusicService.cs#L150

In the block ending with line 150, change/edit to this, note changes added after line 150 as such:

```cs
                        var cur = mp.Current;
                        if (cur.Current == null
                            && !mp.RepeatCurrentSong
                            && !mp.RepeatPlaylist
                            && !mp.FairPlay
                            && AutoDcServers.Contains(guildId)
                            && !mp,Stopped) // hotfix we added
```


Adding this `&& !mp,Stopped) // hotfix we added` line will stop what you describe from happening, because after checking if your bot is to be auto-disconnected from VC, it simply checks and if the bot is not stopped it will proceed to remove it. However it's not a complete fix and I haven't looked much into it.

It won't cause the `.stop` command to destroy the bot/flush the queue with `.autodc` enabled like it does now, but it won't auto-disconnect when the tracks are done because when the tracks _actually_ do end, there is (I think, haven't looked closely) a stop anyway to the player, so basically it never auto- destroys/leaves. So don't consider this anything but me spending a few minutes looking. It will hotfix your issue, if you really use `.stop` a lot.

*You can type `.destroy` and that has to be done when you want it to leave, as it'll stop in the end anyways.*

I am a bit busy right now to look closer and I haven't touched the music module in ages, but I will try to look into it more when I can or if someone else here can feel free, shouldn't be a hard fix at all.
