### ISSUE TITLE
Cleverbot.io instead of official cleverbot api

### ISSUE THREAD

**Issue by TiBarification** [Kwoth/NadekoBot#2095]
The reason is unlimited api requests free of charge.

**Comment by Macley-Kun** [comment]
First: This is a feature, we don't accept features here we do that here: http://feathub.com/Kwoth/NadekoBot

Second: I'm not sure if the quality is as good as cleverbot api. I'm not sure but we actully used to use cleverbot.io but we changed from that. So even if your feature would be getting alot of votes. Kwoth probably would deny it.

**Comment by AnimeCat** [comment]
@Kwoth Opinions?

**Comment by TiBarification** [comment]
>First: This is a feature, we don't accept features here we do that here: http://feathub.com/Kwoth/NadekoBot

I do not think, that it is a feature, it is more relevant to discuss those AI `+` and `-`.

**Comment by Macley-Kun** [comment]
Well you can list the + and - here. Maybe it’ll help to progress the issue/suggestion? No clue what kwoth thinking about it. 

Personally I never had issues with the current cleverbot and other people are also happy with it. But blow or minds :-)

**Comment by Macley-Kun** [comment]
@TiBarification I've bin thinking about this but is it an idea to implement both?
Like: if amount of calls is reached. Then it switches to the .io bot.

Kwoth: you think that's an acceptabel solution?

**Comment by Gremagol** [comment]
I would agree with adding this, because they removed the free 5k plan due to abuse etc.
I'll add a Quote of their website: `NOTE: The Cleverbot API was previously free to use for the first 5000 calls, but constant misuse of this free package, and the maintenance work it caused, mean that it can no longer be offered.`
Another Cleverbot service would be great to have.

**Comment by Kwoth** [comment]
#2323
