### ISSUE TITLE
Creating TCP Server Socket Error for Redis 32

### ISSUE THREAD

**Issue by PopuriAO29** [Kwoth/NadekoBot#2119]
[7124] 20 Feb 10:33:10.875 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server.exe /path/to/redis.conf
[7124] 20 Feb 10:33:10.906 # Creating Server TCP listening socket *:6379: listen: Unknown error

I have started redis-server.exe, but then it closes automatically.

**Comment by Macley-Kun** [comment]
Tried re-installing redis maybe? Seems that due to the lack of a config file, it can't connect/work proper.

**Comment by PopuriAO29** [comment]
I installed git, to starting dotnet run, but it hangs when starting NadekoBot while the port is 6379.
My OS is running Windows 7 Pro x86, i had download bot from this source for git clone.

I also downloaded redis-server.exe x86, but it close automatic even i tried use too many times.

**Comment by Macley-Kun** [comment]
Hey popuri we found your issue! You can close the issue!

Your using windows 7. We don't support windows 7 sadly. 

I checked the docs and i'm not tottaly sure but. You can run nadeko even if you still don't wanna upgrade to windows 8/8.1/10.

You can apperently run nadeko on win7 even on 32-bit using the DOCKER. I still recommend upgrading however because you can use the user friendly nadekobot installer/updater.
https://nadekobot.readthedocs.io/en/latest/guides/Docker%20Guide/

**Comment by PopuriAO29** [comment]
From Source: 32-bit is experimental for nadeko, that's what i installed git.
Redis-server also stopped working, i used laptop model is compaq presario cq43.
Then it should close issue now.
