### ISSUE TITLE
Can't run old Nadekobot/Can't update to newest version

### ISSUE THREAD

**Issue by AlfonzoFrejoles** [Kwoth/NadekoBot#2122]
Whenever I try to run my bot I always get this error message. I'm thinking it's because I need to update it, but I don't think I can considering it's so old. Can I? If so, how?

![image](https://user-images.githubusercontent.com/20632405/36516841-ce413df0-174d-11e8-81bf-b20f54c64e5d.png)

**Comment by shikhir-arora** [comment]
You do need to update it -- if you are on an old version as you are you pretty much should start fresh. The prefixes, modules, and almost every base part of the bot works differently, so it's not a migration that would be straightforward. That error is simply because the bot version you uses an old lib version which connects to an older version of Discord's API.

**Comment by AlfonzoFrejoles** [comment]
Well, that sucks. Thanks for the help!
