### ISSUE TITLE
Presence 0 Servers? Is this a bug?

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#2124]
When I open the BOT long time later
When I hit **_.stats_** look at Presence
Found only **_0 Servers_**
**Text Channels** & **Voice Channels** are displayed normally
Once this happens, there are some instructions that will fail (I tested, as long as the input command will appear out of the picture will be invalid)

example:
.xp
.rip
.bf
Etc. (as long as the input command will appear out of the picture will be invalid) ...

![image](https://user-images.githubusercontent.com/24751265/36533045-64c35e0c-17fd-11e8-9f52-c5e6cadb8857.png)

![image](https://user-images.githubusercontent.com/24751265/36533859-cc54f1dc-17ff-11e8-8151-f36c889ae496.png)

**Comment by Kwoth** [comment]
This means you messed up your images folder. No idea why is it showing 0 servers though

**Comment by hank0531** [comment]
But my images folder are normal
Did not go to change him

**Comment by Macley-Kun** [comment]
Hank, a while ago the images were moved out of the local folder. You still have them but you now have a images.json I believe.

You need to upload your pictures on imgur and use the link **WITH .PNG IN THE URL** and replace that link with the original one in that file. Make sure you do this correct otherwise you screw up the code.

Also I think if I read the log proper. I see you typed in '.rip'. I though the .rip command would only work if you mention someone like: '.rip @ name'. 

Your old pics are still safe in the same folder, they are just not getting used.

**Comment by Macley-Kun** [comment]
@hank0531 your still alive there?

**Comment by hank0531** [comment]
yes

**Comment by Macley-Kun** [comment]
Is your issue solved?

**Comment by Macley-Kun** [comment]
@hank0531 close the issue. If it's solved you close the issue.

**Comment by hank0531** [comment]
@Macley-Kun

**Comment by hank0531** [comment]
@Macley-Kun After repeated testing
The same is true when uploading imgur (there is an image URL in the modified images.json)

**Comment by Macley-Kun** [comment]
I don't follow you. Kwoth and i (and probably lots of others) use imgur for the image.json. I don't get what you mean. Maybe ask a friend who can proper explain what you mean?
