### ISSUE TITLE
[Question] Cross server messaging?

### ISSUE THREAD

**Issue by jennasisis** [Kwoth/NadekoBot#2201]
Basically what is says on the tin, what happened to cross-server messaging on the self-hosted version of the bot?

**Comment by shikhir-arora** [comment]
The ShardCoordinator system created by Kwoth to handle shard restarts handles the logic in Redis, and it's fairly independent from the underlying library. It was made as there were issues with that before on the public bot so Kwoth made his own Shard Manager. Anyways, because of that design it'd be a pain (if not impossible) to do it cross-guild. Maybe on a 0 shard bot - but that's another question altogether.

**Comment by jennasisis** [comment]
Alright then, I *do* have the bot running only on shard 0, so then what would I do for that?

**Comment by Kwoth** [comment]
Cross server messaging wouldn't be that hard to add, again, with pub/sub, but I don't want to do it actually. I will focus on more important features.
