### ISSUE TITLE
Commands Link forwards to Cryptojacking site AuthedMine.com

### ISSUE THREAD

**Issue by rickrussell** [Kwoth/NadekoBot#2214]
https://nadekobot.me/commands takes me a authedmine.com site that's known for cryptojacking.  Authedmine.com is known for monero mining.  Remove this please, otherwise, there's plenty of other Discord bots I can contribute to.

**Comment by TwinDragon** [comment]
You sure? Because I just went there and I'm not seeing anything in ScriptSafe regarding any sort of crypto-mining. Nano Blocker wasn't detecting anything either.

**Comment by shikhir-arora** [comment]
Nadeko's site has a Monero miner you can **optionally** use to earn flowers by logging into the website, authorizing with Discord and accepting a clear term before the miner begins, and the settings panel shows. This is not mining without your consent. You can use your browser's development console and verify that nothing is being done without your explicit consent.

**Comment by Kwoth** [comment]
I'll leave this open so other people can see to avoid even more drama and panic from users who either have malicious intent towards the projects, or simply ignorant yet very vocal about something they didn't even check for themselves.

If you go to nadeko support server on discord, there is a channel called #flower-guide which explains how to earn flowers. **One of them** is optionally mining cryptocurrency on the website. When you open the website, the script does indeed load, but the reason I used authedmine is because you HAVE TO OPT IN in order for it to work, and you do that by clicking "Miner" on the top, logging in with your discord, then turning the miner on, and then you get a huge box over your whole screen telling which explicitly tells you you will be mining cryptocurrency which you have to confirm. It's all OPT-IN aka disabled by default. There is 0 mining happening when you just open the website to check the commands or whatever, and there is no way for a random user to 'accidentaly' turn on the miner.

However, I do understand that some addons (in my opinion very unfairly) block the website as a 'cryptojacking' which is completely false, just because they see the script is being loaded, as there have been many incidents in the past where websites mined crypto without user consent. However authedmine (at least from what i know) seems to be resilient to 'rogue' mining, so I do not know exactly why it's also blacklisted.

The reason a lot of people know about this since few days ago is because i moved from downloading authedmine and putting it on the server, to directly using the authedmine url in the script tag, I did this because some Anti-Viruses see the mining code and just block it, (as there is no way to check if it's safe or not, it's just a mining code), however if i use the official url for authedmine (even though it's generally blacklisted atm) there is a chance it will get unblacklisted in the future if it becomes considered safe for the general public.

For specific details on how the miner works check the #flower-guide channel.

PS. I understand this creates inconvenience for some users and I thought of 2 ways to mitigate this issue
 - Open source the website code so that everyone can actually see how it works
 - Move the miner to an iframe and load it only when the menu is clicked (not sure how practical and convenient this is, but i'll explore this idea)

**Comment by BobbyMan227** [comment]
And how are you suppose to go to support server when your staff team likes to ban people for no legitimate reason?

**Comment by shikhir-arora** [comment]
I think the whole cryptomining thing is overhyped with regards to hijacking. Yes, it can happen, and used to a lot - but nowadays it's pretty easy to tell. As @Kwoth said, there's no way to actually enable the miner without logging into Discord - authorizing through OAuth2 - accepting a clear authorization and then the miner settings shows. There's a verbose log that is shown as well. It's pretty obvious.

Also, https://authedmine.com explains it well. That's why they're not blocked by many of the large blockers. They make it very hard to circumvent authentication.

Even if you forget about all the technicalities, from a practical point it makes no sense. The whole goal of mining here is to earn Nadeko currency (flowers), and that requires you to login with Discord so your account can be credited hourly. It would be pretty bad design if it just mined, said you would get currency and then didn't - my point here is that it's very clear what you're getting into and completely opt-in, with many notices before.

**Comment by skid9000** [comment]
The script should not be loaded by default ...
'Cause now uBlock itself block the load of the page ... :s
<img src="https://puush.tuto-craft.com/7e5z2E.png">

**Comment by Cebtenzzre** [comment]
Yeah, uBlock is not directly blocking the site.  It is blocking _just the authedmine script_ from loading (just in case it were to go ahead and mine coins without permission, I assume).  Then React complains about `CoinHive` not being defined and stops _the entire website_ from loading.

_Regardless_ of whether or not AuthedMine can even be used maliciously; that's bad design.  If one barely related, seemingly non-essential, 3rd-party script fails to load (404, weird JS error, domain resolution issue, etc.) the entire NadekoBot website goes down.  I'd complain about the website needing JavaScript to display literally anything, but I suppose there are benefits to React -- I'm not a web dev whatsoever.

\</rant\>

**Comment by skid9000** [comment]
> It is blocking just the authedmine script from loading
That's what i wanted to say o/

But yeah, the website should have a JS-less version at least for the commands...

**Comment by TwinDragon** [comment]
I'm using a fork of uBlock Origin, NanoBlocker, and it didn't block the page from loading before. I did see that ScriptSafe is listing the domain, so denied it for now. But yeah, the site isn't loading for me now as well.

Web design got way too complicated where it shouldn't have in recent years with websites needing a billion and one scripts just to function from 3rd parties, so it has been getting cumbersome to browse online safely these days. Just bad web design that if one has to rely on 3rd parties to get basic functionality of the pages, then that's just terrible. Most people aren't going to care, but the few that are tech-savvy and power users who do know that javascript, advertising networks, and the like are vulnerable to MitM attacks or the like, we do like to take precautions to at least prevent them when possible..

**Comment by Cephel** [comment]
Please provide a static version of the site that runs without JS.

**Comment by xnaas** [comment]
The biggest issue @Kwoth with the way content is currently loaded, is that many school and corporate networks block this stuff at the firewall level. Even though I **want** to access the commands page at work, it's impossible in the site's current state.

Just some food for thought on the matter.

**Comment by TwinDragon** [comment]
In the meantime though, you can simply just use the `.h` in DM with the bot for commands. May be a little longer to get what you need, but it is the same as the website for the commands.

**Comment by Kronkleberry** [comment]
The commands site is completely useless these days since it was added, not only to the majority of adblocks break the page, I'm starting to get anti-malware applications blocking it too. And even when the whole set is disabled, it doesn't load any of the page past that JS script.

Yes, I realize that I can `.h` to get the bot to spit them out, but if I'm trying to look at a bunch of commands at once, such as when trying to set up server permissions, it's far more tedious than it needs to be, and is an active detriment to using the bot itself.

**Comment by Jarvvski** [comment]
Just dropping my two cents - I don't even use the bot but stumbled across this repo from a friend of mine at work.

Whilst I fully understand the idea of the opt-in and allowing users to support the project through reasonable means such as crypto, I don't think it's the correct implimentation approach. Simply put, many _other_ services block `authedmine.com` at the domain level. People can disable addblockers, but they can't circumvent firewalls and other filters (work/school policies) which rely on upstream block-lists and are normally opt-in for list updates at that.

I haven't seen if you have a repo for your server side code on whatever you're running @Kwoth, but it sounds like it's better to handle it as a session variable and load the script conditionally based on that variable.

Obviously this assumes you have some kind of server side render/pre-processing, and not just a SPA.

If you need a hand, let me know and I can either submit a PR to whatever repo it's on or just gist you some lines.

**Comment by Cephel** [comment]
Wouldn't it be possible to load the coinhive stuff on the fly if the user opts in (and not before) to the service?

**Comment by Foxtrek64** [comment]
This seems to be affected on two surfaces now: adblock and similar, and antivirus. In fact, this is confirmed by Coinhive themselves, the company operating authedmine.com

Site is working in screenshot because I have overridden my AV configuration to "allow but notify."

![image](https://user-images.githubusercontent.com/7003081/40877527-2aaf1af0-6648-11e8-88d0-185e24285541.png)

**Comment by xnaas** [comment]
I'd just like to drop https://xnaas.info/nadeko/ as an option for people who cannot access the main site at all. You're stuck needing to ctrl+f, but at least it loads! 😉 

Per last time I mentioned it:

> Edit: Please don't try and rape my site, but anyone is welcome to use https://xnaas.info/nadeko/ as a very basic version of https://nadekobot.me/commands should they desire. 👍 **_I won't support it and I don't plan on making it fully functional_**, but was tired of not being able to use the normal web version.

**Comment by Jarvvski** [comment]
@xnaas if it's just HTML that you're using there, just host it on github pages instead of worrying about your web server being taken down via GETs on a HTML page.

**Comment by xnaas** [comment]
muh effort tho 😛 

You can right-click and save the page and upload if you'd like. 👍

**Comment by Kwoth** [comment]
![chess](https://user-images.githubusercontent.com/2537696/41583517-fa7668cc-73ce-11e8-8734-8d0a33c2ea5b.gif)

Updated the website. Miner will be in iframe. If you're not using it, website will work normally with any adblock/antivirus software enabled ^^

**Comment by Kwoth** [comment]
Oh right. It can't work in the background anymore like this (if you remember before, when you start it and minimize, there was a loading icon which told you you're still mining). I don't think I can do that anymore.

**Comment by Jarvvski** [comment]
@Kwoth thank you very much. I'm now able to access the site from behind my work's firewall

👍 to discussing problems and getting good solutions

**Comment by Cephel** [comment]
dank

**Comment by xnaas** [comment]
Good lord, thank you, @Kwoth. 👏 🎉
