### ISSUE TITLE
Song Requests

### ISSUE THREAD

**Issue by XKPlayzYT** [Kwoth/NadekoBot#223]
Hello, my name is XKPlayzYT. 

I am putting in a issue request of the song requests for the latest release all the way up to the latest pre-release of NadekoBot. It recognizes the request command, but doesn't play any sound at all. It also doesn't leave as soon as I do !m s or !m skip. Mind fixing this please? Thanks!

Kind Regards,
XKPlayzYT

**Comment by Kwoth** [comment]
Either you didn't setup ffmpeg correctly, or google api key, or nadeko doesn't have permissions. Sometimes this happens when you don't add root certs on ubuntu. Also if you are getting unknown opcode9 error. Restarting and retrying a few times will solve it. It will be fixed in the new reease.

Those are all the reasons it can happen because of.

As for not leaving, that is intentional. Use !m d to leave
