### ISSUE TITLE
The command `.vcrole` resets on its own removing bot's ability to give and take roles from a user when it joins or leaves a vc

### ISSUE THREAD

**Issue by amanrajput72** [Kwoth/NadekoBot#2330]
The command `.vcrole` resets on its own removing bot's ability to give and take roles from a user when it joins or leaves a vc

**Comment by zergling-man** [comment]
Can you provide more detail on this? Eg. under what circumstances does it reset? Is it when the bot restarts? When the shard restarts? Or just after some amount of time (during which you can confirm no restart occurred)?

**Comment by amanrajput72** [comment]
I've confirmed, it happens when the bot restarts. Hope it'll be fixed soon
cause I really use that vcrole command a lot. Thanks!

**Comment by zergling-man** [comment]
Sounds like it's not being written to the DB. Investigate the VcRoleInfo table as you set it up, and after it restarts.

**Comment by amanrajput72** [comment]
Yes. it is not being written to the DB for some reason. Can you do
something?

**Comment by zergling-man** [comment]
Could be an issue with redis. Could be an  issue with permissions. Do other things (currency changes, `.bce`) get written successfully?

**Comment by shikhir-arora** [comment]
There are some things intentionally designed or done because of the setup with Redis that aren't persistent. Most things are, but for example the `ErrorColor` and `OkColor` aren't going to persist -- solution there is simply having those as startup commands (`.bce OkColor #000000` etc.) 

With the way the lib/what's in redis works I wouldn't be surprised, I haven't looked into it closely for the vcrole but I am pretty sure that it's intentional. Redis doesn't persist like that anyways, so the stuff that does is in the DB. Reaction roles do persist, for example, but the way `.vcrole` is designed probably does not have a way to persist on restart.

**Comment by Kwoth** [comment]
Can't reproduce. Works fine. Make sure you don't have unsaved changes in the database.
