### ISSUE TITLE
24/7 Hosting

### ISSUE THREAD

**Issue by LeoDoesThings** [Kwoth/NadekoBot#2354]
Hi, 

I've really been trying to put off asking this question, but is there ANY way to host NadekoBot other than my PC **FOR FREE**. I know this might seem like a stupid question, but I have spent the past month searching for a free alternative to DigitalOcean and none of them are any help at all.

pls help me im poor

(also I use a 2013 MacBook Air, so you have a Windows answer then it is not going to be much help)

**Comment by TwinDragon** [comment]
This isn't the place to ask this, but I'll sorta answer.

No, there really isn't. Bandwidth isn't free when it comes to VPS, shell hosting, etc. I do recall there was a free SSH service at one point, but how well it worked, I don't know. I never really used it anyway because I have a second tower I use to host my bot off of a Debian install.

If you want to host it for "free", your best bet is to find a cheap desktop computer for a couple hundred bucks, wipe Windows if you prefer, install a lite Linux distro of your choice and go from there. Otherwise, you can just use the public Nadekobot or something.

**Comment by LeoDoesThings** [comment]
I know that glitch.com is a free web hosting service that can be turned into a host for Discord bots, but it doesn't support C# and limits you to 128MB.

**Comment by LeoDoesThings** [comment]
I probably sound really picky, but that is only for 12 months. I need a permanent solution.

**Comment by Kaoticz** [comment]
As far as I know, you can stay in the free tier indefinitely ONLY if you use micro EC2 instances. But I might be wrong there, can someone confirm it plz?

**Comment by Macley-Kun** [comment]
There are two options i can give you, because when I started my project I did the same.
1. Use SkySilk, you can get the vps you need and nadeko works fine on the 1GB memory plan (this is free during beta).
HOWEVER! This beta will end soon, and due to the compile process, you sadly need double the memory of the forever lasting Free plan. 
Fix? Well, only if someone knows how to reduce the memory usage of the nadekobot when it’s being compiled.

2. Heroku! Heroku offers you a platform that has 1gb memory, 2 cores and unlimited bandwidth. However getting nadekobot to work on it requires a person who is experienced with nadeko, c# and Heroku. The only person I know who can pull this off actully made a nadeko working on that platform.
BUT He only updated it to version 1.3b. So you have a very oudated one. 
The only solution to that problem is to get it to work for yourself. But that’s an incredible difficult task that even I can’t do.

Hope this shit post brought you something. I can tell you now there isn’t any other option left.

**Comment by Mr-Deej** [comment]
Try out cloud.google.com this is what I have managed to host some Discord bots on. I am not familiar enough to attempt installing Nadeko, but they give you a free 12 month credit that never charges your card after. the service is always free until upgraded. So yea if you want to try it with nadeko try it out.
