### ISSUE TITLE
NadekoBot Updater Rework

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#2460]
### The updater is lacking heavily.  
It should support hosting multiple bots and have much more powerful functionality.  
- This could be done via some sorts of tabs possibly? Or buttons on the side which would show bot's version, owner name, and the name of the bot.   
- You should be able to "open containing folder" which would open the bot's folder and also "edit credentials" which would open credentials.json for editing. (Bonus: Open db button which would open the database using the sqlitebrowser?)  
- One of the tabs should be an "add button" in the form of a plus sign or similar, which would let you add another "tab" (another bot). 
- There should be a regular option to 'download' the bot but also, after the download is done, in order to make it easy for new users to set up the bot, you should be either to normally edit 'credentials' or to "authorize" which would let you 'log in' - you would type in your bot's name, choose the avatar, and upon pressing "create",  or an equivalent button, the updater would create a bot app in your name, and fill in owner id, token and client id appropriately.  
- The design needs to be in-line with the designs we have so far.  
- The console output would be embedded into the application itself (as a sub-tab while one of the bot's is selected possibly?)  

What if we made it an asp.net core application and make it support both windows and linux? This way we'd have one updater which allows you to host multiple bots without knowing anything about linux, and would be stupidly user-friendly.

**Comment by xnaas** [comment]
Possibility: Perhaps a simple dropdown?

Dropdown List:
* Bot 1
* Bot 2
* New Bot

Then just any relevant parts of the UI?

The only reason I could see to avoid tabs is once you get 3-5 bots, even with tiny tabs, I'm sure that would soon become very crowded and poor UX.

I don't know. Just a thought.

**Comment by rjt-rockx** [comment]
Also, I don't think it's possible to programmatically create a new Bot Application for the user and get the token, they would need to do that themselves.

**Comment by MaybeGoogle** [comment]
> The console output would be embedded into the application itself (as a sub-tab while one of the bot's is selected possibly?)

Instead of this, if it's possible, just hide the console completely. A sizable number of people have asked if there's any way to close cmd but keep the bot up. Also, instead of embedding the console which takes up space, have a button to open it as a pop-up. I'm thinking a row of buttons for opening NadekoBot/, credentials.json, NadekoBot.db, and console.

Also a wild-ish feature: allow users to deploy a bot remotely on a linux server. The same general steps used in linuxAIO.sh can be selected in a way similar to <https://ffmpeg.zeranoe.com/builds/>, except that each row to the right only appears after you've selected an option. 
NadekoBot/ would open in filezilla, credentials.json and NadekoBot.db would be ftp'd and opened normally. Under the buttons for opening these, maybe have another button to upload or smth. For console, either just provide a logged-in ssh console or go straight to logs if that's possible.

**Comment by rjt-rockx** [comment]
The pm2 API would help with that ^

Server configuration might vary depending on the type of server being used to host Nadeko
So people could be using SSH, SFTP with RSA key exchange, Docker, Heroku, etc

Procedures would vary for each so automating only a single procedure wouldn't work out. 

Feel free to DM me any concepts for the UI btw, I'll try making a few mockups

**Comment by Macley-Kun** [comment]
@rjt-rockx you made some mockups a while ago? Maybe post them here for some feedback?
