### ISSUE TITLE
repeat commands not working (again)

### ISSUE THREAD

**Issue by EricZTams** [Kwoth/NadekoBot#2467]
Exact same problem as #2351 except different person.

Spamming `.reprm 1` didnt work. No response is given for any of the commands. Still public Nadeko.
Apparently it was repeating with a deleted role tag in the message successfully, then stopped working.

sid: 277465273852887040

Im thinking maybe theres a bad repeat blocking it somehow... if you want to try clearing it and it works, quick fix (and possibly just a good feature to have) is a repeatclear command.

**Comment by TorqaL** [comment]
I saw that there was a post for repeat commands not working properly, so I am adding onto this post instead of creating a new one.
I have this command running in my bot-commands channel to repeat every half hour. I have implemented `-n` in order to only repeat if the last message is not the repeat message. This did not work, as it continued to spam my channel. I removed this, and tried without `-n` and as I expected, it spammed the channel. In this picture, no one else wrote a command, or typed in the channel, but the bot continued to spam.

Here is the command I am using, but I am assuming there is a bug with `-n`:

`.repeat -i 30 -m "Type .userinfo to see your profile
Type ?customs to see all the possible roles
Type .lcr to list helpful information for PoGo
Visit channel #commands-faq for more bot commands" -n`

![capture](https://user-images.githubusercontent.com/38439052/43644098-858fc756-96fb-11e8-8627-b87ba2786e16.PNG)

I only have two repeats running on my server, the other repeats every 5 hours, in a different channel, in a different category. That, too, has not been working properly, as it is spamming the channel with `-n`.

![capture1](https://user-images.githubusercontent.com/38439052/43644333-61b06498-96fc-11e8-9432-b675f16044ed.PNG)

The command is as follows:

`.repeat -i 300 -m " @Unverified Please post a screenshot of your trainer name and level. 
If you are level 40, please post two screenshots: Your trainer name / level, and also your total exp.
If you want to stop receiving those notifications, simply verify with us, and you will stop receiving them. :slight_smile: " -n`

This is public Nadeko. I am not too sure what I am doing wrong, if I am doing anything wrong or if this is a bug with the `-n` command. Thanks!

**Comment by Kwoth** [comment]
I've made some fixes to repeaters. Wait for next update
@TorqaL Your issue is also fixed in the next update.

**Comment by TorqaL** [comment]
Sounds good - Thank you @Kwoth looking forward to the update.
