### ISSUE TITLE
.crca interfere with other commands even if actualcustomreactions is disabled

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#2518]
Repo steps:

.acr someCommonText temp_respond
.crca 1
.cm actualcustomreactions disable #thischannel
.acr newCommand I'm using someCommonText

will not add the newCommand

**Comment by MaybeGoogle** [comment]
This is expected behavior. Custom reactions take precedence over normal commands. If custom reactions were to be enabled, the command still would not run. 

Having the precedence switch for cases like this would be possible ig, but would probably require a rewrite of sections of command handler and priority system.

I think the flow goes something like
Does this message fit a custom reaction? yes. set as a cr message, skip all the normal command stuff.
Oh wait a sec, are custom reactions blocked? yes. 
Aight late block it.
done.

**Comment by willysunny** [comment]
technically speaking, it should be the other way around. commands should always have higher priority than custom reactions. Or else I could technically render all command unusable by creating a crca custom reaction for all commands.

**Comment by Kwoth** [comment]
No, google is right.
