### ISSUE TITLE
Music - youtube player cuts out on long songs/sometimes fails to play items in playlist and needs to be restarted

### ISSUE THREAD

**Issue by v23gamer** [Kwoth/NadekoBot#321]
Not sure if this has to do with the youtube api flakiness or not, but on long-ish songs the bot sometimes cuts off in the middle and immediately starts the next song. No errors in the log, however it does seem suspicious that all of the songBuffer.ContentLength are very close to each other (about 3,140,000, poopybuffer initialized at 4mb?). I'll try building the bot with a larger initialized poopybuffer i guess and see if it fixes the issue. I'm seeing the issue with 5 min long songs.

The other issue is that twice now on long playlists the bot failed to play next song and stopped working, and had to be restarted. http://puu.sh/p9NLz/942190f8aa.png
This one is more likely to be related to youtube api flakiness, however the second error seems like a bug in the bot.

**Comment by Kwoth** [comment]
It is a known issue.

About cutting off - what usually fixes it for people is changing discord server location to amsterdam/singpore. We won't track music issues since they aren't going to be fixed until we move to discord.net 1.0 and rewrite music completely.

About songs not being queued (not found in the dictionary), it pretty much means it can't find that song for one of many reasons. Either somehow blocked from streaming, or its blocked in your country.
