### ISSUE TITLE
!!q music plays and ends right away

### ISSUE THREAD

**Issue by CaptainPantsu** [Kwoth/NadekoBot#444]
Reading from the permission files.
Permission initialization complete.
>> Cmd: !!queue
Msg: !!q https://www.youtube.com/watch?v=Zlc28Nd8xG0
Usr: CaptainPantsu [168089983570280448]
Srvr: Underground Loli Society [172143992828329984]
-----
Buffering errored: The system cannot find the file specified
Buffering done. [0]
Prebuffering done? in 5000
Song finished. [0]
Awiting buffer task
Buffer task done.

**Comment by erikm6872** [comment]
It looks like the issue is that the system can't find the FFmpeg executable. It's expecting ffmpeg.exe to be located in the NadekoBot\NadekoBot\bin\Debug\ directory, and if it's not there it throws this error.

**Comment by erikm6872** [comment]
I'm guessing it's an issue with the sketchy custom FFmpeg installer they want you to use for some reason. The download at the [official FFmpeg site](https://ffmpeg.org/download.html) works just fine, so I'm not sure why the custom installer is necessary or useful.

**Comment by Kwoth** [comment]
@CaptainPantsu if you downloaded and ran ffmpeg installer from the comprehensive guide, you must restart your PC. If you downloaded it from the official site, you can either add its bin folder to the PATH environment variable or copy the contents of the bin folder next to your nadekobot.exe

@erikm6872 because people can't follow a video on how to add something to environment variables. We get at least 5 questions with this exact same issue per day on the discord server, installer completely solves that issue.

**Comment by erikm6872** [comment]
@Kwoth Fair enough. Did you write the installer? If so you could probably add that project to the solution so that it's included with the git repo instead of sending people to a third party download site. 

If this is a common issue, throwing a custom exception with a message along the lines of "FFmpeg executable not found. Follow these steps: ..." might be a bit more helpful than the generic "The system cannot find the file specified" error and could probably help reduce the volume of questions on your server. It looks like whenever this happens it throws a `System.ComponentModel.Win32Exception`, so catching that specific exception and handling it or throwing your own exception would be pretty easy.

**Comment by Kwoth** [comment]
@erikm6872 Community member wrote the installer. 

Good idea, I'll add it to the repo.

Also pushed better console error. Thanks for the feedback :)
