### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by v3Monsta** [Kwoth/NadekoBot#475]
I tried seeing if this was on my end, but even after resetting the bot entirely I still received the same error message.

Stacktrace: http://hastebin.com/rokojulolu.xml | From errors.txt
Additional: https://s31.postimg.org/7du6uuujf/Untitled.png | From console output

OS: Ubuntu Server 16.10

**Comment by Kwoth** [comment]
It pretty much means song cannot be found. Sometimes it works on another try, sometimes you need to modify search parameter, in this case try another link. It's videolibrary being unable to find the song's audio stream, i could try dropping the audio quality restriction which would maybe resolve a small part of those, but I think it mostly occurs due to blocked videos.

**Comment by v3Monsta** [comment]
Tried another song and it worked, of course. In retrospect I should've tried that before coming here but either way thank you for the quick reply.
