### ISSUE TITLE
How to summon the bot to a channel

### ISSUE THREAD

**Issue by ClientSideOnly** [Kwoth/NadekoBot#492]
I was curious as to how to add the bot to my voice channel, then play music. I can't seem to find the right commands on your [https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md](url) command list here.
Thanks in advance

**Comment by Soundofdarkness** [comment]
You need to have the bot self hosted . Then just use  `!!q`

**Comment by miraai** [comment]
In case you got the bot from Carbonitex or from our github/help, music module is disabled because its to expensive to be on so many servers. 

If you want to have music, you will have to host the bot yourself. How to do that, you can check the wiki page.

In case you are hosting the bot, just queue a song with `!!q song`.

**Comment by Kwoth** [comment]
or type `-commands Music` to see the music commands : )
