### ISSUE TITLE
[Feature Request] Toggle to Allow Anyone to .acr

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#572]
Much like in #388 where a toggle was added to have DMs forwarded to *all* owners, I'm asking for something similar with `.acr`.

I get that there is a quote system with `..` and `. . .`, but none of my users like that *at all*. Neither do I. It's super annoying and makes actually calling up commands all the time a pain in the ass.

I don't think *everyone* should have access to `.dcr` or `.ecr`, but the option to allow anyone to use `.acr` would be nice. It could then be controlled via the permissions system too, which would be nice.

**Comment by Kwoth** [comment]
I had an idea which will be added in 1.0, so i will close this. 

Basically, instead of hard-coding permissions for administration commands and other ones, I'll just add those permissions as a default permission in the permissions system, like NSFW is for example (disabled on server by default). So, only owner will have access to those commands, but it will be actually be changeable since its a part of the permissions.

**Comment by xnaas** [comment]
Acceptable answer. 1.0 can't come soon enough. 😢
