### ISSUE TITLE
Control multiple NadekoBot instances

### ISSUE THREAD

**Issue by sebastianbinder** [Kwoth/NadekoBot#614]
Hey there,
right now it is no problem letting multiple NadekoBots join one single Discord server. But is there any possibility to "chat" with them separately? E.g. entering .uid now gets a response from every single instance. Any way to "chat" with just one instance?

**Comment by appelemac** [comment]
yes, change the prefixes :1234:

**Comment by sebastianbinder** [comment]
Oh great! Thanks!

**Comment by sebastianbinder** [comment]
Any possibility to change prefixes in NadekoBot 1.0?

**Comment by Kwoth** [comment]
In order to open NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db (1.0) or data/NadekoBot.sqlite (0.9.x), you need to download and install sqlite browser from here http://sqlitebrowser.org/ Open the database with it, make changes to any settings you want and click on "write changes" at the top.

**Comment by sebastianbinder** [comment]
Great. Thank you!
