### ISSUE TITLE
Can't find the quotes file?

### ISSUE THREAD

**Issue by keirajasmin** [Kwoth/NadekoBot#677]
So, I have Nadeko on my laptop running for a server and one of the members decided to add a bunch of quotes that no one is happy with (they're either personal, inappropriate or not even actual quotes) and we've tried ..qdel (all 3 of the bot owners tried it, and the person who made the quotes tried it) but it doesn't delete the quotes, it just sends a message saying "done." and we end up finding the quote again even though it was supposedly deleted, so my last resort is to find where quotes are stored and delete them that way (and I can't find where that is) or to make an entirely new bot, what do I do?

(I noticed other people were having this issue as well, I tried updating the bot, restarting after "deleting" a quote, none of that works, it's just a broken function at this point. Everyone I've read having the same issue also is looking for the file quotes are stored and there have been no answers on how to find them)

**Comment by Kwoth** [comment]
This might be due to some whitespaces in the original quote. 

Anyway, you can download sqlite browser http://sqlitebrowser.org/ , install it and open `data/NadekoBot.sqlite` file in your nadekobot folder. Select UserQuote table, find the unwanted quotes, select them and click "delete record" button in the top right corner.

**Comment by keirajasmin** [comment]
Thank you! I was able to delete the quotes.
