### ISSUE TITLE
Token validation failed

### ISSUE THREAD

**Issue by fkndean** [Kwoth/NadekoBot#714]
![image](https://cloud.githubusercontent.com/assets/20934051/19623493/8737ef46-9899-11e6-86ff-96482df5e4fa.png)

I am 100% sure my token is correct. This is for Nadeko 1.0

**Comment by Nitix** [comment]
1. Update your bot
2. Try again
3. Profit

4? Come back

**Comment by fkndean** [comment]
1. On latest branch for 1.0.
2. Tried with different bot apps (tokens).
3. No profit.
4. I came back.

**Comment by Nitix** [comment]
You may have something wrong with your configuration, my bot is running with latest commit. Also check others properties as client Id, bot Id.

**Comment by fkndean** [comment]
My configuration isn't wrong. Tried the docker version and it worked fine with my credentials.

**Comment by Kwoth** [comment]
@fkndean Are you sure you're putting your credentials.json in the right place? You should be using `dotnet run` and running it from src/NadekoBot, and that's where credentials.json should be

**Comment by Kwoth** [comment]
Also, make sure you are using bot token, not user token, because we don't support user tokens atm

**Comment by AraHaan** [comment]
The problem is they are storing credentials.json file that they configured probably in the folder of ``NadekoBot.dll`` or whatever extension on the platform they use. So, placing it in the right folder can help also #720 helpx fix any crash related to logging in even if the Websockket is nor Supported any exception in the Sharded Client file should now be handled properly to show the same stack trace (just in a safe non crashign way) NadekoBot will still close though when it happens.

**Comment by Kwoth** [comment]
Solved?

**Comment by fkndean** [comment]
Yes it has been solved. Thanks all.
