### ISSUE TITLE
[QUESTION] About flowers drop rate

### ISSUE THREAD

**Issue by Kr0NiCk** [Kwoth/NadekoBot#744]
Is there anyway that you can possible change the flowers drop rate instead of being 2%?

regards,

**Comment by Kwoth** [comment]
if you are bot owner (hosting the bot on your own PC) then you can. Atm there is no easy way to do it, but there will be at one point. You need to open and edit NadekoBot.db (BotConfig) table, and you will be able to. Also, If you are using public bot, I am looking into a way to make servers able to create their own independent economy, to free yourself from evil Kwoth Bank's grip. 

In order to open NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db (1.0) or data/NadekoBot.sqlite (0.9.x), you need to download and install sqlite browser from here http://sqlitebrowser.org/ Open the database with it, make changes to any settings you want and click on "write changes" at the top. Restart the bot afterwards.
