### ISSUE TITLE
How to access config (db) in 1.0?

### ISSUE THREAD

**Issue by roxaskeyheart** [Kwoth/NadekoBot#809]
Hi there,

I have just migrated successfully to 1.0 from 0.9, however I'm really scratching my head as to how I would update config now, in particular the currency name/sign as well as the 8ball entries. I have found default values in the .cs files under Services/Database/Models but these seem to be initialises and don't update any live values.

So my question is how do I update these particular settings now in 1.0? Any help would be appreciated.

**Comment by Kwoth** [comment]
config is now in the database itself.

In order to open NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db (1.0) you need to download and install sqlite browser from here http://sqlitebrowser.org/ Open the database with it, make changes to any settings you want and click on "write changes" at the top.

Never edit .cs files.

**Comment by roxaskeyheart** [comment]
Aweseome, that is exactly what I was after.

You're probably already all over this but you should add the tip about sqlite browser in the documentation at some point. 👍

**Comment by Kwoth** [comment]
@samdivaio is the docs wizard, if he permits :D

**Comment by ChiefKeef97** [comment]
i am using the updated version1.4 and having the same issue. i cannot find the .db file to up update certain settings. thanks for any help in advance
