### ISSUE TITLE
How to change nadekoflowers to something else?

### ISSUE THREAD

**Issue by wolfbun** [Kwoth/NadekoBot#814]
I self host nadekobot and I want to change nadekoflowers to something else, how do i go about doing this?

**Comment by fkndean** [comment]
Check your config.json for `CurrencyName` or I believe it is in the DB now in 1.0? You can browse through `NadekoBot.db` by downloading SQLite Browser

**Comment by Kwoth** [comment]
In 0.9 it's as fkndead said, config.json in data folder.

in 1.0 it's in the .db file

In order to open NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db (1.0) you need to download and install sqlite browser from here http://sqlitebrowser.org/ Open the database with it, make changes to any settings you want and click on "write changes" at the top.
