### ISSUE TITLE
Can't add custom reactions

### ISSUE THREAD

**Issue by RalphORama** [Kwoth/NadekoBot#884]
I set up nadekobot so I'm the owner account and invited it to my server, but I can't get it to add custom reactions. Every time I run `.acr <trigger> <message>`, I get the error "Insufficient permissions. Requires Bot ownership for global custom reactions, and Administrator for guild custom reactions."

I know I'm the owner, however, as I can run `.die` and the bot restarts. What's wrong?

**Comment by samdivaio** [comment]
And that happened in your own server or on your friends server?
Also check if you have perms on both then test if it doesn't work restart the bot.

**Comment by Kwoth** [comment]
use .acr in DMs to make global custom reactions and those require you to have bot ownership.

`.acr` in server channels require you to have administrator privilege. It's tested and it works. If you really are a server owner, try giving yourself a role with administration checked in order to make server-sepecific custom reactions.

**Comment by RalphORama** [comment]
I tried it on my own server, and it worked fine. I'm having the issue on a friend's server.

I've set the permrole properly (running `;permrole` doesn't return an error), set myself as owner in `credentials.json`, but I'm not sure if there's a step I'm missing
