### ISSUE TITLE
Custom categories for Hangman

### ISSUE THREAD

**Issue by dnaf** [Kwoth/NadekoBot#942]
Having custom categories for Hangman instead of just using the defaults would be pretty rad 😎

**Comment by Kwoth** [comment]
If you're self-hosting, just edit the data/hangman.json file.You can't change it on public nadeko.

**Comment by dnaf** [comment]
I tried, I couldn't seem to add custom categories. Correct me if I'm wrong, but [looking at the code](https://github.com/Kwoth/NadekoBot/blob/dev/src/NadekoBot/Modules/Games/Commands/Hangman/HangmanGame.cs#L26) it seems that the categories are hard-coded in, meaning I shouldn't be able to add more just by editing the JSON file.

**Comment by shikhir-arora** [comment]
You can still do it. Just add the category to the `HangmanGame.cs` file you linked. For example if you wanted to add something called Other, just add it after Things on the `HangmanGame.cs` file making sure to append all entries besides the last one with a comma. 

You have to keep track of this manually because Nadeko will update this file when you update it. That's why source code changes aren't always recommended unless you know what you're doing :-) 

Anyways, the JSON file needs to be edited then and you need to use JSON format with your new category. Look at the `data/hangman.json` and you can see how it's done. Just standard JSON - you can copy the format for one of the other categories, say Animals. Copy and change it to your category - like  Other - and then add content as normal.

Just remember you need to manually keep track of the changes to source files as mentioned. I do this a lot but it requires you keep track of the changes every update.

**Comment by Kwoth** [comment]
I totally forgot, that wasn't supposed to be implemented like that in the end, it was just a temporary thing, I'll fix this

**Comment by Kwoth** [comment]
fixed. You can just edit hangman.json now and you will be able to play with those new categories.
