### ISSUE TITLE
!!radio pause problem

### ISSUE THREAD

**Issue by radiodrag** [Kwoth/NadekoBot#943]
While no one is on the channel, the streaming (!!ra command) is pausing but even if it says "resume" the music don't resume and i need to restart the bot completely for it to work again.

So, i wonder if there's a possibilty to not pause while there's no one or to mute itself to save bandwith and avoid "pause bugs" on streams?

**Comment by SillyBirds** [comment]
What settings/changes would you recommend for ffmpeg? listening to a radio directly usually gives me no buffer issues, but with the bot that's not usually the case...

**Comment by shikhir-arora** [comment]
A few things - I work a lot with audio engineering and plan to make a video guide using Nadeko to demonstrate the best practices for hosting MusicBots in general, however:

- The latency between the **voice chat server** and **where your Nadeko** (applies to any musicbot) is very important. Your personal latency to the Discord voice chat server is important but not as critical as the latency between the bot and the server.

- Discord uses OPUS to send audio - it's hit or miss for music; great for voice however depending on how you configure OPUS (which we don't have control over), it can be good to OK. Also, remember, currently the maximum bitrate you can have on Discord (excluding partner servers) is 96kbps. Back to this in a minute.

The default configuration for Nadeko is the recommended setup:

```C#
        const int milliseconds = 20;
        const int samplesPerFrame = (48000 / 1000) * milliseconds;
        const int frameBytes = 3840; 
```

With a default prebuffer of 1 megabyte (configured as 1 MiB) and a default `OutputPCMStream` of 960 frames which corresponds to 20ms.

These are good settings. In case you are wondering, we get 20ms by taking our sample rate (48000 per second/ 1000) which yields us 48 frames/ms.

[Normally, 16-bit, 2 channels is (16*2*1024 samples/buffer)/8 (to go to bytes) = 4,096 bytes].

The reason we have 3,840 is because we have a 20ms delay, which results in 48 frames/ms * 20ms = 960 frames. Two stereo channels, so 960 * 2 = 1,920 frames. At 16-bit, (each bit is 2 bytes), our total bytes out is 1,920 * 2 = **3,840** and that's how we get the frameBytes that is used by default.

- The pause you mention is due to accumulating buffers. You can play around with all the settings, but as I mentioned, what is important is latency between the servers. If you halve all these values (that is lower our ms delay to 10, bringing our frameBytes to 1,920 total) you will notice that the music is much quicker. However, this is the lowest latency that is supported by OPUS and isn't that realistic. It works, and you will notice that almost-instantaneous buffering and very little pause if you have everything setup as best as you can, but even with servers in the same region as Discord's it's not ideal to have a 10ms buffer. 

- The other variable you can play around with is the pre buffer, which is 1 megabyte (1MiB) by default. You don't want this to go that high. This is what is being buffered by ffmpeg prior to starting a song. 

- Remember all these numbers are related (ms, samples/frame, frameBytes, and PCMStream output which is 960 frames by default (not *bytes* - it is 960 * 2ch * 2 bytes/16bit = 3,840 bytes).

===========

What I'm working on now to improve it and will push to the public repo when I have finished + tested:

- [ ]  Making a guide on how to best setup your bots for quality as mentioned;]

- [ ] **Discord uses OPUS** as I mentioned. Currently, it is outputting a standard PCM stream. For the best quality, Discord.net (the C# library used in Nadeko) supports DirectOPUS. I am working on that codebase to change so that the audio is output directly as an OPUS stream to Discord. This will improve things across the board.

===========


By the way, I've followed these practices that I'll be outlining and never had an issue with the bot besides the occasional bug. However, I have streamed many radio stations that are native 192-320kbps directly using `!!radio` with Nadeko for days without any problems. Also, pausing isn't as much of an issue if the buffers are correct. Like I said, you can reduce everything by half to 10ms/1,920 bytes/480 frames for the outputPCMStream, but that is pushing it with Discord and your setup needs to be very optimal as it's essentially pushing double the speed (10ms delay, so 10ms update time vs. 20ms).

Besides that, you are limited by Discord's 96kbps current bitrate and encrypted OPUS streams. They do have a good variety of server regions and latency is good on the side of their platform.


Sorry for the long post. Wanted to lay everything out! 👍

**Comment by SillyBirds** [comment]
@shikhir-arora Thanks for that awesome reply.

I have to admit I'm new to this, as I'm only using Linux because of Nadeko, so I'm going to need fairly straightforward instructions (or name where the things need to be worked on).

For your info, the bot uses a German droplet, with the discord server being in the Netherlands (it's a partner server, so it has up to 128k for the audio channels), so distance should be an issue. 

With that said, what should I do? 😄

**Comment by shikhir-arora** [comment]
Glad I could help :-) 

I will have the video guide out __very__ soon (hopefully later today) and will update here as soon as that is done. I'm also working on the other two things mentioned (direct OPUS encoding out & utilizing the `Latency` measures) with Discord.net and through ffmpeg. 

Yes, that is a good setup. I have something similar - one server in Germany and one in Amsterdam with our voice channel in Central Europe.

*128k is neat. Totally jealous!* I hope Discord will offer higher bitrates, even if it comes at an optional premium.

I think it's better off holding on for the guide since it'll be done very soon and covers it for you, at least what you can do without the "major" changes mentioned that I'm working on and should have something testable soon.

If you really want to play around and feel comfortable doing so, the files that are pertinent are in `../src/Modules/Music/Classes/Song.cs` as well as `../src/Modules/Music/Classes/SongBuffer.cs`

Specifically in `Song.cs` you likely don't want to mess with the values I posted above because you can only halve it (technically; you can do whatever but the standard lower than 20ms is 10ms, the lowest feasible one). But as I said 10ms on Discord server's are still not cutting it. You may have better connections though as a partner server, so no harm trying. Edit the lines I posted above to:

```C#

        const int milliseconds = 10;
        const int samplesPerFrame = (48000 / 1000) * milliseconds;
        const int frameBytes = 1920; 
```

and also a line at the bottom called something like `outputPCMStream[x]` where x is 960 by default; with the above changes edit that to 480 (half).

**Restart Nadeko and proceed normally** You will notice right away what I mean with the "fast pause" - however if it becomes too choppy (the *debug* window in Discord on the bottom left is excellent) then switch back to the original mentioned in my last post (the default).

The other thing you can do is change the buffer (play with this if you wish): in `Song.cs` you will see a value `1.MiB` with a comment \\ fast connections can easily handle this  => you can change this to something smaller; again, being vary of the considerations I posted above. If you do change that line, use power of two numbers (like 1024, 512, etc.) if you wish and replace `MiB` with `KiB` (these are [Kibibytes](https://en.wikipedia.org/wiki/Kibibyte) - you can try `512.KiB` if you wish. 

In `SongBuffer.cs` the only things you can really change right now I'd bother with are the `buffer[]` which is:

```C#

                   byte[] buffer = new byte[81920];
                   int currentFileSize = 0;
                   ulong prebufferSize = 100ul.MiB();
```

by default. You can change 81920 (though again that's the standard config) to something lower - I have mine set to 2^16 = 65,536 and my prebuffersize slightly smaller. But YMMV, and remember these are source changes. But you can easily revert back. 

I would change the `Song.cs` first, leave the `SongBuffer.cs` (unless you do a lot of `!!radio`) and listen to it on your server since it may have a slightly better advantage. And then see how it goes from there. Remember, 10ms is a *quick* buffer - almost zero delay between servers and that's the lowest OPUS supports, as does Discord's official wrappers.

Thanks for your interest! The actual OPUS & Latency var changes will make the biggest change __by far__ because the native OPUS stream especially coupled with the latency updates in (essentially) real time will be a nice improvement. Also some small cleanups like #947 which was fixed earlier that should help further. 🎧

**Comment by SillyBirds** [comment]
Awesome, thanks 👍 I'll wait for your guide then!

**Comment by Kwoth** [comment]
#1053 for tracking music issues, most of them are the same issue

**Comment by Dommage** [comment]
I would really love a !!nopause option I'm using NadekoBot to stream my online radio to a channel and really don't want it to be pause when no one's listening.
