### ISSUE TITLE
Auto Assign Role not working

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#952]
![adsiz](https://cloud.githubusercontent.com/assets/21060067/21769597/29566c40-d688-11e6-914d-4b20731d6855.png)

**Comment by DaYWhiTe** [comment]
There are necessary permits but it is not work

**Comment by Kwoth** [comment]
I don't think there are. 403 happens when bot can't do something it was supposed to do due to permissions. Make sure you're giving the right role permissions. Also make sure it's as high as it can be in the role hierarchy
![image](https://cloud.githubusercontent.com/assets/2537696/21770425/7fe2538a-d683-11e6-971f-c3e1c7fa1758.png)

**Comment by DaYWhiTe** [comment]
I and the bot are present in all the roles but it is not work
