### ISSUE TITLE
Song Not Found error?

### ISSUE THREAD

**Issue by AlyssHashizawa** [Kwoth/NadekoBot#968]
Ok so i just setup nadeko bot and thought i had everything set up correctly but for some reason the bot will take my youtube link and say that the song is not found. If anyone knows how to fix this i would appreciate it. xD
![song not found](https://cloud.githubusercontent.com/assets/25089674/21909580/2568990c-d8de-11e6-9b0b-78403441cacd.png)

**Comment by shikhir-arora** [comment]
You need to use the proper playlist link.

`!!playlist http://www.youtube.com/playlist?list=PLgrYntDWyYDdHwZney5QoTDFQrphRmYoK`

Not something like this:

http://www.youtube.com/watch?v=ILwOQV32rHg&list=FLLpWow4PGIVkCJifJxrMfwA

**Comment by AlyssHashizawa** [comment]
I used both, it won't play even just single songs for some reason it keeps telling me the FFMPEG wasn't installed correctly but i did everything the guide had said to do. 
![ffmeg issue](https://cloud.githubusercontent.com/assets/25089674/21909835/305c0c6c-d8df-11e6-9525-b6deec7a0750.png)

**Comment by Kwoth** [comment]
@AlyssHashizawa 
![image](https://cloud.githubusercontent.com/assets/2537696/21910267/9454d97e-d91b-11e6-8e03-89fbac363910.png) remove &list at the end of the link and everything after it.
so you should type `!!q https.......?v=LSNHaguaOCE`

**Comment by AlyssHashizawa** [comment]
Now it's just bringing up FFMPEG isnt installed correctly 
![ffmeg issue](https://cloud.githubusercontent.com/assets/25089674/21910629/77923914-d8e2-11e6-8b93-a8f5d820e074.png)

**Comment by shikhir-arora** [comment]
Is your stuff playing despite the verbose errors?

**Comment by AlyssHashizawa** [comment]
no, but it queue's the song and says it's playing 
![playing](https://cloud.githubusercontent.com/assets/25089674/21911011/31231172-d8e4-11e6-9b34-0a4b96e7eac9.png)

**Comment by Kwoth** [comment]
restart your PC after installing ffmpeg

**Comment by AlyssHashizawa** [comment]
I have restarted my computer

**Comment by shikhir-arora** [comment]
@AlyssHashizawa Restart the bot. Make sure it's offline, then bring it back on. Let me know if you still have issues.  Type in `!!q The Name Of A Song` and if that doesn't work at all; type `!!stop` followed by `!!destroy` and then `!!q some regular YouTube song URL`

-------

@Kwoth aside: I never had issues, but I changed a few things to a new commit (that is not part of the release yet) for both playlist regex and a bit of a cleanup on the regular `!!q` regex.

Just confirming **every** command (swap songs, skipping 50 songs ahead, removing songs, mixing SoundCloud and YouTube, etc.) works before I make a push request.

So far all of those commands work perfectly, even with a 400-queue playlist. There are some verbose errors thrown but it doesn't affect anything; it's because in large playlists if the API rejects certain URL's (usually only a few in hundreds), this will display that.

**Comment by AlyssHashizawa** [comment]
still getting the same results after restarting the bot completely.
![results](https://cloud.githubusercontent.com/assets/25089674/21913200/9573f4c8-d8f0-11e6-92b9-b790b3e8dd17.png)

**Comment by shikhir-arora** [comment]
Looks like it's a buffer issue. I'll have to finish my basic guide, but see my comments on #943 

This shouldn't have anything to do with the recent regex updates. You get that error when the buffer needs to substantially fill up to keep up. And it also could be an ffmpeg problem as it is stating because I've never seen that output before re: ffmpeg. I'll try to do some digging.

**Comment by Kwoth** [comment]
Open your command prompt and type `ffmpeg`, what does it say?

**Comment by AlyssHashizawa** [comment]
Not recognized as an Internal or External command, operable program or batch file.

**Comment by Kwoth** [comment]
You didn't install ffmpeg. Installer is broken atm. You need to install using manual method https://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/ scroll ALL the way down (Manual ffmpeg install)

**Comment by AlyssHashizawa** [comment]
Just leaving this comment showing that I found what I did wrong incase someone else has the same problem I had. The look of my Environment variables is different from the one on the gif in the guide so i didnt know where to put the file location so i had to kind of play around with it. Figured I would respond to let you guys know I was the mess up. Thanks for the help <3 ^-^
![ffmpeg file location](https://cloud.githubusercontent.com/assets/25089674/21916776/6a5b31f8-d908-11e6-9ea4-a5f8110fc8f6.png)
